export const en = {
  : "────────────────────────────",
  12345_ABCDEFGHIJKLMNOPQRSTUVWYXZABCDEFGHIJKLMNOPQRSTUVWXYZ_12345: "12345 abcdefghijklmnopqrstuvwyxzABCDEFGHIJKLMNOPQRSTUVWXYZ 12345",
  1BB152_ON_DA812D1BB152_ON_DA812D: "[#1BB152 on #DA812D]#1BB152 on #DA812D!",
  1_1_IS_NOT_3: "1 + 1 is not 3",
  1_CUESHEET_BLOCK_FOUND: "> 1 CueSheet block found",
  1_SEEKTABLE_BLOCK_FOUND: "> 1 SeekTable block found",
  20S_64S_NCALLS_TOTTIME_PERCALL_STATE_REGEX: "%-20s %-64s ncalls  tottime  percall' % ('state', 'regex",
  7S_7S_7S_S_FREQ_SIZEK_AVGSIZE_TYPE: "%7s  %7s  %7s  %s\" % (\"Freq\", \"Size(k)\", \"AvgSize\", \"Type",
  ABORTED: "Aborted.",
  ABORTED_2: "Aborted...",
  ACTION_PLANNED: "Planned action: {action}",
  ACTIVE_DB_NOT_FOUND: "ACTIVE_DB_NOT_FOUND",
  ALABEL_MUST_NOT_END_WITH_A_HYPHEN: "A-label must not end with a hyphen",
  ALL_CONNECTION_ATTEMPTS_FAILED: "All connection attempts failed",
  ALREADY_RESOLVED: "already resolved",
  ALREADY_WAITING_FOR_A_PONG_WITH_THE_SAME_DATA: "already waiting for a pong with the same data",
  ANCHOR_IS_NOT_SPECIFIED_FOR_ALIAS: "anchor is not specified for alias",
  ANCHOR_MUST_NOT_BE_EMPTY: "anchor must not be empty",
  ANNOTATION_IS_NOT_PERMITTED_AS_A_FIELD_KEYWORD_ARGUMENT: "\"annotation\" is not permitted as a Field keyword argument",
  ANYIO_BACKEND_MUST_BE_EITHER_A_STRING_OR_TUPLE_OF_STRING_DICT: "anyio_backend must be either a string or tuple of (string, dict)",
  ANY_CANNOT_BE_INSTANTIATED: "Any cannot be instantiated",
  AN_ID3_TAG_ALREADY_EXISTS: "an ID3 tag already exists",
  AN_MP4_TAG_ALREADY_EXISTS: "an MP4 tag already exists",
  AN_OBJECT_OTHER_THAN_LIST_FOUND_BEHIND_THIS_KEY: "An object other than list found behind this key",
  APEV2_KEY_MUST_BE_STR: "APEv2 key must be str",
  APPLY_DELETIONS: "Apply deletions",
  APPLY_DELETIONS_WARNING: "This operation will permanently delete files",
  APPLY_PENDING_OPERATIONS: "Apply pending operations",
  APP_DIRS_WITH_OPTIONAL_VERSION: "-- app dirs (with optional 'version')",
  ARCHIVE_ROOT_NOT_SET: "ARCHIVE_ROOT_NOT_SET",
  AREA_OUTSIDE_OF_FILE: "area outside of file",
  ARGUMENT_IS_MARKED_AS_EXPOSED_BUT_DOES_NOT_HAVE_A_NAME: "Argument is marked as exposed, but does not have a name.",
  ARRAY_IS_TOO_LARGE: "Array is too large",
  ASYNCIORUN_CANNOT_BE_CALLED_FROM_A_RUNNING_EVENT_LOOP: "asyncio.run() cannot be called from a running event loop",
  ASYNC_GENERATOR_FIXTURE_DID_NOT_STOP: "Async generator fixture did not stop",
  ASYNC_ITERABLE_MUST_CONTAIN_BYTES_OR_STR: "async iterable must contain bytes or str",
  ASYNC_ITERABLE_MUST_CONTAIN_UNIFORM_TYPES: "async iterable must contain uniform types",
  ATOMIC_WRITES_ONLY_MAKE_SENSE_WITH_WMODE: "Atomic writes only make sense with `w`-mode.",
  ATTEMPTED_TO_ACQUIRE_AN_ALREADY_HELD_LOCK: "Attempted to acquire an already held Lock",
  ATTEMPTED_TO_CONVERT_A_CALLBACK_INTO_A_COMMAND_TWICE: "Attempted to convert a callback into a command twice.",
  ATTRIBUTE_NOT_FOUND: "Attribute not found",
  AT_LEAST_ONE_HASH_MUST_BE_PROVIDED: "At least one hash must be provided",
  AT_LEAST_TWO_GENRE_IDS_ARE_REQUIRED: "At least two genre IDs are required",
  AUTH_HOOKS_MUST_BE_CALLABLE: "Auth hooks must be callable.",
  AUTOCOMMAND_REQUIRES_A_MODULE_NAME_ARGUMENT: "autocommand requires a module name argument",
  A_DISTRIBUTION_NAME_IS_REQUIRED: "A distribution name is required.",
  A_SAMPLE_RATE_VALUE_OF_0_IS_INVALID: "A sample rate value of 0 is invalid",
  A_VORBIS_COMMENT_ALREADY_EXISTS: "a Vorbis comment already exists",
  BAD_CHECKSUM: "bad checksum",
  BAD_CONTENTLENGTH: "bad Content-Length",
  BATCHED_INCOMPLETE_BATCH: "batched(): incomplete batch",
  BEFORE__GET_PACKAGE_DATA: "before _get_package_data():",
  BIN_IS_TOO_LARGE: "Bin is too large",
  BITS_USED_HAS_TO_BE_0: "bits used has to be > 0",
  BLACK_ON_GREENBLACK_ON_GREEN: "[black on green]black on green!",
  BLACK_ON_WHITEBLACK_ON_WHITE: "[black on white]black on white!",
  BLOCK_IS_TOO_LONG_TO_WRITE: "block is too long to write",
  BLUEBLUE: "[blue]blue!",
  BLUE_ON_GREENBLUE_ON_GREEN: "[blue on green]blue on green!",
  BOK_LOUDLY_CRYING_FACE: "[b]OK :loudly_crying_face:",
  BOLDRESET_FILLFIRST_INITIAL_INDENT: "{bold}{}{reset}', fill(first, initial_indent='* ",
  BOLD_BLACK_ON_CYANBOLD_BLACK_ON_CYAN: "[bold black on cyan]bold black on cyan!",
  BOLD_GREENCOVID_DELETED_SUCCESSFULLY: "[bold green]Covid deleted successfully",
  BOLD_GREENHELLO_WORLDBOLD_GREEN: "[bold green]hello world![/bold green]",
  BOLD_GREENHELLO_WORLDBOLD_GREEN_2: "'[bold green]hello world![/bold green]'",
  BOLD_MAGENTAHELLO_WORLD: "[bold magenta]Hello World[/]",
  BOLD_WHITE_ON_BLUEBOLD_WHITE_ON_BLUE: "[bold white on blue]bold white on blue!",
  BOLD_YELLOWBOLD_YELLOW: "[bold yellow]bold yellow!",
  BOOL_UNDEFINED_WHEN_ITERABLE_TOTAL_NONE: "bool() undefined when iterable == total == None",
  BRIGHT_YELLOWBRIGHT_YELLOW: "[bright_yellow]bright_yellow!",
  BTN_BACK: "Back",
  BTN_CANCEL: "Cancel",
  BTN_FINISH: "Finish",
  BTN_LOAD_PRESET: "Load preset",
  BTN_NEXT: "Next",
  BTN_PROCEED_TO_SCAN: "Proceed to scan",
  BTN_SAVE_PRESET: "Save preset",
  BUILD_TAG_BUILDNUMBER_MUST_START_WITH_A_DIGIT: "Build tag (build-number) must start with a digit.",
  BUILD_TAG_MUST_BEGIN_WITH_A_DIGIT: "build tag must begin with a digit",
  BULK_APPLY: "Apply bulk",
  BULK_MARK_DELETE: "Mark for deletion",
  BYTECOMPILING_IS_DISABLED: "byte-compiling is disabled.",
  BYTES_TYPE_INPUT_MUST_BE_BYTES: "bytes_type', 'Input must be bytes",
  BYTES_TYPE_INPUT_MUST_BE_VALID_BYTES: "bytes_type', 'Input must be valid bytes",
  BYTE_SIZE_COULD_NOT_PARSE_VALUE_AND_UNIT_FROM_BYTE_STRING: "byte_size', 'could not parse value and unit from byte string",
  BZ2_MODULE_IS_NOT_AVAILABLE: "bz2 module is not available",
  CACHED: "Cached!",
  CALLBACK_IS_NOT_A_COMMAND: "Callback is not a command.",
  CALLED: "called",
  CANCELED_BY_USER: "canceled by user",
  CANNOT_ACCEPT_CONTEXT_AND_KWARGS: "cannot accept context and kwargs",
  CANNOT_ADD_MIDDLEWARE_AFTER_AN_APPLICATION_HAS_STARTED: "Cannot add middleware after an application has started",
  CANNOT_BE_CHECKED_AGAINST_SELF_OUTSIDE_OF_A_METHOD_CALL: "cannot be checked against Self outside of a method call",
  CANNOT_CALL_RECEIVE_ONCE_A_DISCONNECT_MESSAGE_HAS_BEEN_RECEIVED: "Cannot call \"receive\" once a disconnect message has been received.",
  CANNOT_CALL_SEND_ONCE_A_CLOSE_MESSAGE_HAS_BEEN_SENT: "Cannot call \"send\" once a close message has been sent.",
  CANNOT_COMBINE_PATH_WITH_USER_OR_LOCAL: "Cannot combine '--path' with '--user' or '--local'",
  CANNOT_DECODE_DATA: "Cannot decode data",
  CANNOT_ENCODE_OBJECTS_THAT_ARE_NOT_2TUPLES: "cannot encode objects that are not 2-tuples",
  CANNOT_ERASE_PARTIAL_TYPES: "Cannot erase partial types",
  CANNOT_EXTRACT_SYMLINK_AS_FILE_OBJECT: "cannot extract (sym)link as file object",
  CANNOT_FIND_A_PATHFINDER_IN_SYSMETA_PATH: "Cannot find a PathFinder in sys.meta_path",
  CANNOT_FIND_ENV_FILE: "cannot find .env file",
  CANNOT_GENERATE_SCHEMA_FOR_INVALID_SCHEMA_THIS_IS_A_BUG_PLEASE_REPORT_IT: "Cannot generate schema for invalid_schema. This is a bug! Please report it.",
  CANNOT_HANDLE_ERASED_TYPE: "Cannot handle erased type",
  CANNOT_HANDLE_PARTIAL_TYPE: "Cannot handle partial type",
  CANNOT_HANDLE_WORDS_WITH_FEWER_THAN_TWO_SEPARATORS: "Cannot handle words with fewer than two separators",
  CANNOT_HAVE_TWO_NARGS_0: "Cannot have two nargs < 0",
  CANNOT_ORDER_METHOD_TARGETS_BY_MRO: "Cannot order method targets by MRO",
  CANNOT_PARAMETERIZE_A_CONCRETE_INSTANTIATION_OF_A_GENERIC_MODEL: "Cannot parameterize a concrete instantiation of a generic model",
  CANNOT_RESCHEDULE_AFTER_EXIT_FROM_CONTEXT_MANAGER: "cannot reschedule after exit from context manager",
  CANNOT_RESCHEDULE_EXPIRED_TIMEOUT: "cannot reschedule expired timeout",
  CANNOT_SEND_A_REASON_WITHOUT_A_CODE: "cannot send a reason without a code",
  CANNOT_SHIFT_TIMEOUT_IF_DEADLINE_IS_NOT_SCHEDULED: "cannot shift timeout if deadline is not scheduled",
  CANNOT_SPECIFY_BOTH_CONFIG_AND_KEYWORD_ARGUMENTS: "Cannot specify both `config` and keyword arguments",
  CANNOT_SPECIFY_BOTH_DEFAULT_AND_DEFAULT_FACTORY: "cannot specify both default and default_factory",
  CANNOT_SUBCLASS_SPECIAL_TYPING_CLASSES: "Cannot subclass special typing classes",
  CANNOT_TAKE_A_CONCATENATE_OF_NO_TYPES: "Cannot take a Concatenate of no types.",
  CANNOT_UNPACK_FROM_MULTIBYTE_OBJECT: "cannot unpack from multi-byte object",
  CANONICAL_GENRE_NAME: "Canonical genre name",
  CANT_CHANGE_EXTRACTION_PATH_FILES_ALREADY_EXTRACTED: "Can't change extraction path, files already extracted",
  CANT_HAVE_UNBUFFERED_TEXT_IO: "can't have unbuffered text I/O",
  CANT_INSTALL_WHEN_CROSSCOMPILING: "Can't install when cross-compiling",
  CANT_LISTDIR_A_FILE: "Can't listdir a file",
  CANT_RECEIVE_DATA_WHEN_PEER_STATE_IS_ERROR: "Can't receive data when peer state is ERROR",
  CANT_SEND_DATA_WHEN_OUR_STATE_IS_ERROR: "Can't send data when our state is ERROR",
  CANT_SEND_TRAILERS_TO_HTTP10_CLIENT: "can't send trailers to HTTP/1.0 client",
  CANT_SUBCLASS_GROUPEDMETADATA_WITHOUT_IMPLEMENTING___ITER__: "Can't subclass GroupedMetadata without implementing __iter__",
  CANT_SYNC_TO_MPEG_FRAME: "can't sync to MPEG frame",
  CAN_NOT_COMBINE_USER_AND_TARGET: "Can not combine '--user' and '--target'",
  CAN_NOT_MIX_NUMERAL_TYPES_IN_A_RIGHTTOLEFT_LABEL: "Can not mix numeral types in a right-to-left label",
  CAN_ONLY_HAVE_ONE_OF_BYTES_UPDATE_UPDATE_TO: "Can only have one of --bytes --update --update_to",
  CAN_ONLY_WRAP_READWRITE_METHODS: "Can only wrap read/write methods",
  CAUGHT_HANDLED_EXCEPTION_BUT_RESPONSE_ALREADY_STARTED: "Caught handled exception, but response already started.",
  CA_DATA_NOT_SUPPORTED_IN_OLDER_PYTHONS: "CA data not supported in older Pythons",
  CA_DIRECTORIES_NOT_SUPPORTED_IN_OLDER_PYTHONS: "CA directories not supported in older Pythons",
  CHARDET_IS_NOT_VENDORED_BY_PIP: "chardet is not vendored by pip",
  CHUNK_WITHOUT_CRLF: "chunk without CRLF",
  CLAMPING_IS_NOT_SUPPORTED_FOR_OPEN_BOUNDS: "Clamping is not supported for open bounds.",
  CLASS_VAR: "class_var",
  CLEANUP_CANDIDATE_DIR: "Candidate directory: {path}",
  CLEANUP_INVALID_TARGET: "Invalid target directory",
  CLEANUP_MODE_CONFLICT: "Choose either --apply or --dry-run",
  CLEANUP_PLANNED_AND_REMOVED: "Cleanup planned: {planned}, removed: {removed}",
  CLEANUP_SCAN_RESULT: "Directories eligible for cleanup: {count}",
  CLEAR_SELECTION: "Clear selection",
  CLIENT_MAX_WINDOW_BITS_MUST_BE_BETWEEN_8_AND_15: "client_max_window_bits must be between 8 and 15",
  CLIENT_PRIVATE_KEY_IS_ENCRYPTED_PASSWORD_IS_REQUIRED: "Client private key is encrypted, password is required",
  CLOSE_FRAME_TOO_SHORT: "close frame too short",
  CODE_MUST_BE_0127: "code must be 0~127",
  CODE_MUST_BE_INT: "code must be int",
  COLOR_ERROR_VALUE_IS_NOT_A_VALID_COLOR_ALPHA_VALUES_MUST_BE_A_VALID_FLOAT: "color_error', 'value is not a valid color: alpha values must be a valid float",
  COLOR_ERROR_VALUE_IS_NOT_A_VALID_COLOR_ALPHA_VALUES_MUST_BE_IN_THE_RANGE_0_TO_1: "color_error', 'value is not a valid color: alpha values must be in the range 0 to 1",
  COLOR_ERROR_VALUE_IS_NOT_A_VALID_COLOR_COLOR_VALUES_MUST_BE_A_VALID_NUMBER: "color_error', 'value is not a valid color: color values must be a valid number",
  COLOR_ERROR_VALUE_IS_NOT_A_VALID_COLOR_STRING_NOT_RECOGNISED_AS_A_VALID_COLOR: "color_error', 'value is not a valid color: string not recognised as a valid color",
  COLOR_ERROR_VALUE_IS_NOT_A_VALID_COLOR_TUPLES_MUST_HAVE_LENGTH_3_OR_4: "color_error', 'value is not a valid color: tuples must have length 3 or 4",
  COMMAND_ALIASES: "Command Aliases",
  COMMAND_HAS_NO_NAME: "Command has no name.",
  COMMAND_IS_AN_ABSTRACT_CLASS: "Command is an abstract class",
  CONCRETE_NAMES_SHOULD_ONLY_BE_GENERATED_FOR_GENERIC_MODELS: "Concrete names should only be generated for generic models.",
  CONFIG_ALREADY_EXISTS_USE_FORCE_TO_OVERWRITE: "Config already exists. Use --force to overwrite.",
  CONFIG_AND_MODEL_CONFIG_CANNOT_BE_USED_TOGETHER_CODECONFIGBOTH: "\"Config\" and \"model_config\" cannot be used together', code='config-both",
  CONFIG_VARS: "config vars:",
  CONFIRM_DELETION_WARNING: "I understand this operation is irreversible",
  CONFLICTING_CONTENTLENGTH_HEADERS: "conflicting Content-Length headers",
  CONNECTING_THROUGH_A_SOCKS_PROXY_REQUIRES_PYTHONSOCKS: "connecting through a SOCKS proxy requires python-socks",
  CONNECTION_CLOSED_DURING_OPENING_HANDSHAKE: "connection closed during opening handshake",
  CONNECTION_CLOSED_WHILE_READING_HTTP_HEADERS: "connection closed while reading HTTP headers",
  CONNECTION_CLOSED_WHILE_READING_HTTP_REQUEST_LINE: "connection closed while reading HTTP request line",
  CONNECTION_CLOSED_WHILE_READING_HTTP_STATUS_LINE: "connection closed while reading HTTP status line",
  CONNECTION_LOST: "Connection lost",
  CONNECTION_NAME_FIELD_IS_NOT_A_STRING: "connection_name field is not a string",
  CONSIDER_UPGRADING_PEDRO: "   Consider upgrading Pedro.",
  CONSOLE: "console",
  CONSTRAINING_TO_A_SPECIFIC_TIMEZONE_IS_NOT_YET_SUPPORTED: "Constraining to a specific timezone is not yet supported",
  CONST_IS_REMOVED_USE_LITERAL_INSTEAD_CODEREMOVEDKWARGS: "`const` is removed, use `Literal` instead', code='removed-kwargs",
  CONTENTLENGTH_AND_TRAILERS_DONT_MIX: "Content-Length and trailers don't mix",
  CONTEXT_MUST_INCLUDE_A_REQUEST_KEY: "context must include a \"request\" key",
  CONTINUATION_LINE_AT_START_OF_HEADERS: "continuation line at start of headers",
  CONTROL_FRAME_TOO_LONG: "control frame too long",
  COULD_NOT_CHANGE_MODE: "could not change mode",
  COULD_NOT_CHANGE_MODIFICATION_TIME: "could not change modification time",
  COULD_NOT_CHANGE_OWNER: "could not change owner",
  COULD_NOT_DETERMINE_APPROPRIATE_FILE: "Could not determine appropriate file.",
  COULD_NOT_DETERMINE_EDITOR_TO_USE: "Could not determine editor to use.",
  COULD_NOT_FIND_A_FREE_PORT: "could not find a free port",
  COULD_NOT_FIND_BINARY_READER_FOR_INPUT_STREAM: "Could not find binary reader for input stream.",
  COUNT_IS_NOT_VALID_WITH_IS_FLAG: "'count' is not valid with 'is_flag'.",
  COUNT_IS_NOT_VALID_WITH_MULTIPLE: "'count' is not valid with 'multiple'.",
  CSV_EXPORT_DONE: "CSV exported to {path} ({count} rows)",
  CSV_IMPORT_DONE: "Imported {count} planned actions from CSV",
  CYGWIN_GCC_CANNOT_BE_USED_WITH_COMPILERMINGW32: "Cygwin gcc cannot be used with --compiler=mingw32",
  DAEMON_HAS_DIED: "Daemon has died",
  DAEMON_IS_UP_AND_RUNNING: "Daemon is up and running",
  DAEMON_KILLED: "Daemon killed",
  DAEMON_STARTED: "Daemon started",
  DAEMON_STOPPED: "Daemon stopped",
  DATABASE_SCHEMA_IS_NEWER_THAN_THIS_PEDRO_VERSION: "⚠ Database schema is newer than this Pedro version",
  DATA_CONTAINS_INCONSISTENT_TYPES: "data contains inconsistent types",
  DATA_IS_A_DICTLIKE_OBJECT: "data is a dict-like object",
  DATA_MUST_BE_BYTES: "data must be bytes",
  DATA_MUST_BE_STR_BYTESLIKE_OR_ITERABLE: "data must be str, bytes-like, or iterable",
  DATA_MUST_BE_STR_BYTES_ITERABLE_OR_ASYNC_ITERABLE: "data must be str, bytes, iterable, or async iterable",
  DATA_MUST_BE_STR_BYTES_OR_ITERABLE: "data must be str, bytes, or iterable",
  DATA_MUST_BE_STR_OR_BYTES: "data must be str or bytes",
  DATA_MUST_BE_STR_OR_BYTESLIKE: "data must be str or bytes-like",
  DATA_MUST_HAVE_BYTES_TYPE: "data must have bytes type",
  DATA_MUST_NOT_BE_A_STRING: "Data must not be a string.",
  DATA_RECEIVED_IS_NOT_VALID_JSON: "Data received is not valid JSON",
  DB_ACTIVE: "Active database: {path}",
  DB_CLEARED: "Active database cleared",
  DB_PATH_MISSING: "DB_PATH_MISSING",
  DB_SET: "Active database set to: {path}",
  DECODING_ERROR: "decoding error",
  DECOMPRESSION_FAILED: "decompression failed",
  DEFAULT_MUST_BE_CALLABLE: "default must be callable",
  DEFERRAL_TRACE: "Deferral trace:",
  DEPENDENCY_GROUPS_TABLE_IS_NOT_A_MAPPING: "Dependency Groups table is not a mapping",
  DEPENDENCY_GROUP_NAME_IS_NOT_A_STR: "Dependency group name is not a str",
  DEPRECATED: "deprecated",
  DEPRECATED_OPTIONS_CANNOT_USE_PROMPT: "`deprecated` options cannot use `prompt`.",
  DICTIONARY_IS_EMPTY: "dictionary is empty",
  DICT_IS_TOO_LARGE: "Dict is too large",
  DID_NOT_RECEIVE_A_VALID_HTTP_REQUEST: "did not receive a valid HTTP request",
  DID_NOT_RECEIVE_A_VALID_HTTP_RESPONSE: "did not receive a valid HTTP response",
  DIM_BRIGHT_YELLOWDIM_BRIGHT_YELLOW: "[dim bright_yellow]dim bright_yellow!",
  DISCARD_SHOULDNT_STEP_AFTER_EOF: "discard() shouldn't step after EOF",
  DISCRIMINATOR_CAN_ONLY_BE_USED_WITH_UNION_TYPE_WITH_MORE_THAN_ONE_VARIANT: "`discriminator` can only be used with `Union` type with more than one variant",
  DISTANCE_MUST_BE_AT_LEAST_0: "distance must be at least 0",
  DISTINFO_DIRECTORY_NOT_FOUND: ".dist-info directory not found",
  DIST_MUST_BE_A_DISTRIBUTION_INSTANCE: "dist must be a Distribution instance",
  DMYPY_IGNORING_REPORT_GENERATION_SETTINGS_STARTRESTART_CANNOT_GENERATE_REPORTS: "dmypy: Ignoring report generation settings. Start/restart cannot generate reports.",
  DOCTOR_REPORT_WRITTEN_TO: "Doctor report written to:",
  DOESNT_SUPPORT_TAGS: "doesn't support tags",
  DOMAIN_TOO_LONG: "Domain too long",
  DONT_DO_THIS: "don't do this",
  DRY_RUN_NOT_SUPPORTED_YET: "Dry-run not supported yet",
  DSF_CHUNK_TRUNCATED: "DSF chunk truncated",
  DSF_DATA_HEADER_NOT_FOUND: "DSF data header not found",
  DSF_DATA_HEADER_SIZE_MISMATCH: "DSF data header size mismatch",
  DSF_DSD_HEADER_NOT_FOUND: "DSF dsd header not found",
  DSF_DSD_HEADER_SIZE_MISMATCH: "DSF dsd header size mismatch",
  DSF_FMT_HEADER_NOT_FOUND: "DSF fmt header not found",
  DUMPS_KWARGS_KEYWORD_ARGUMENTS_ARE_NO_LONGER_SUPPORTED: "`dumps_kwargs` keyword arguments are no longer supported.",
  DUPLICATE_LABELS_IN_PROJECT_URLS: "duplicate labels in project urls",
  DUPLICATE_RG_PACKET: "Duplicate RG packet",
  DUPLICATE_SH_PACKET: "Duplicate SH packet",
  EACH_ELEMENT_OF_LIBRARIES_MUST_A_2TUPLE: "each element of 'libraries' must a 2-tuple",
  EACH_ITERABLE_MUST_HAVE_TWO_OR_MORE_ITEMS: "each iterable must have two or more items",
  EDITABLE_REQUIREMENTS_ARE_NOT_ALLOWED_AS_CONSTRAINTS: "Editable requirements are not allowed as constraints",
  EITHER_FAMILY_OR_LOCAL_HOST_MUST_BE_GIVEN: "Either \"family\" or \"local_host\" must be given",
  ELEMENT_IS_NOT_A_COMBINATION_OF_ITERABLE: "element is not a combination of iterable",
  ELEMENT_IS_NOT_A_PRODUCT_OF_ARGS: "element is not a product of args",
  EMAILVALIDATOR_IS_NOT_INSTALLED_RUN_PIP_INSTALL_PYDANTICEMAIL: "email-validator is not installed, run `pip install 'pydantic[email]'`",
  EMAILVALIDATOR_IS_NOT_INSTALLED_RUN_PIP_INSTALL_PYDANTICEMAIL_2: "email-validator is not installed, run `pip install pydantic[email]`",
  EMAILVALIDATOR_VERSION_20_REQUIRED_RUN_PIP_INSTALL_U_EMAILVALIDATOR: "email-validator version >= 2.0 required, run pip install -U email-validator",
  EMPTY_DOMAIN: "Empty domain",
  EMPTY_FILE: "empty file",
  EMPTY_FILENAME: "Empty filename",
  EMPTY_HEADER: "empty header",
  EMPTY_LABEL: "Empty Label",
  EMPTY_LABEL_2: "Empty label",
  EMPTY_PACKAGE_RESTRICTION: "empty package restriction",
  EMPTY_PAGES_LIST_NOT_ALLOWED: "empty pages list not allowed",
  ENCODING_ARGS_INVALID_FOR_BINARY_OPERATION: "encoding args invalid for binary operation",
  END_COLUMN_MUST_BE_AFTER_COLUMN: "\"end_column\" must be after \"column\"",
  END_LINE_MUST_NOT_BE_BEFORE_LINE: "\"end_line\" must not be before \"line\"",
  END_MUST_BE_NONE_OR_A_STRING: "end must be None or a string",
  END_OF_FILE_HEADER: "end of file header",
  ENTRYPOINT_OBJECTS_ARE_IMMUTABLE: "EntryPoint objects are immutable.",
  ENTRY_POINTS_MUST_BE_LISTED_IN_GROUPS: "Entry points must be listed in groups",
  ERRORS_ENCOUNTERED_WHILE_EXAMINING_DEPENDENCY_GROUPS: "errors encountered while examining dependency groups:",
  ERROR_CANNOT_LOAD: "Cannot load configuration",
  ERROR_CANNOT_SAVE: "Cannot save configuration",
  ERROR_COPYING_C_STRING_FROM_CFSTRINGREF: "Error copying C string from CFStringRef",
  ERROR_DB_NOT_FOUND: "Database not found at {path}",
  ERROR_DB_NOT_SET: "Database not configured (MUSIC_DB not set)",
  ERROR_GENERIC: "An unexpected error occurred",
  ERROR_INITIALIZING_CTYPES: "Error initializing ctypes",
  ERROR_INVALID_PLAN: "Invalid startup plan",
  EVAL_STRTRUE_IS_ONLY_SUPPORTED_WITH_FORMATFORMATVALUE: "eval_str=True is only supported with format=Format.VALUE",
  EXCCLASS_OPTION_IS_NOT_AN_EXCEPTION_CLASS: "excclass option is not an exception class",
  EXPECTED_ARRAY: "Expected array",
  EXPECTED_AT_LEAST_ONE_NONNONE_STYLE: "expected at least one non-None style",
  EXPECTED_A_CONTINUATION_FRAME: "expected a continuation frame",
  EXPECTED_BYTESLIKE_OBJECT_NOT_INT: "expected bytes-like object, not int",
  EXPECTED_BYTES_WEBSOCKET_MESSAGES_BUT_GOT_TEXT: "Expected bytes websocket messages, but got text",
  EXPECTED_FILL_STRICT_OR_IGNORE: "Expected fill, strict, or ignore",
  EXPECTED_MAP: "Expected map",
  EXPECTED_RIFFWAVE: "Expected RIFF/WAVE.",
  EXPECTED_SERVER_MAX_WINDOW_BITS: "expected server_max_window_bits",
  EXPECTED_SERVER_NO_CONTEXT_TAKEOVER: "expected server_no_context_takeover",
  EXPECTED_TEXT_WEBSOCKET_MESSAGES_BUT_GOT_BYTES: "Expected text websocket messages, but got bytes",
  EXPECTED_TO_RAISE: "Expected to raise",
  EXPECTED_TWO_COLUMNS_FOR_DEFINITION_LIST: "Expected two columns for definition list",
  EXPECTED_WEBSOCKET_UPGRADE: "Expected WebSocket upgrade",
  EXPECTED___FSPATH___TO_RETURN_A_FILENAME: "expected __fspath__() to return a filename",
  EXPORT_ACTION_COPY: "Copy file",
  EXPORT_ACTION_DELETE: "Delete file",
  EXPORT_ACTION_SKIP: "Skip file",
  EXPORT_ACTION_UPDATE: "Update existing file",
  EXPORT_CONFIRMATION_REQUIRED: "Please confirm this export plan before running it",
  EXPORT_DRY_RUN_NOTICE: "This is a dry-run export plan. No files have been copied or deleted yet",
  EXPORT_NOT_ALLOWED_YET: "Execution of export plans is not yet enabled",
  EXPORT_ORPHAN_DIR_DELETE_HINT: "This directory can be safely removed",
  EXPORT_ORPHAN_DIR_EMPTY: "Directory will become empty after export",
  EXPORT_ORPHAN_DIR_ONLY_ART: "Directory contains only album art files",
  EXPORT_REASON_FILTERED_OUT: "File was excluded by export filters",
  EXPORT_REASON_NO_RECOMMENDED_PATH: "File has no recommended destination path",
  EXPORT_REASON_ORPHAN_FILE: "File exists in target but not in export plan",
  EXPORT_REASON_SIZE_MATCH: "File already exists with the same size",
  EXPORT_REQUIRES_CONFIRMATION: "This export plan requires explicit confirmation before execution",
  EXPORT_SUMMARY_DIRS_TO_CREATE: "Directories to create",
  EXPORT_SUMMARY_DIRS_TO_DELETE: "Directories to delete",
  EXPORT_SUMMARY_ESTIMATED_BYTES: "Estimated bytes to transfer",
  EXPORT_SUMMARY_FILES_TOTAL: "Total files in export plan",
  EXPORT_SUMMARY_TO_COPY: "Files to copy",
  EXPORT_SUMMARY_TO_DELETE: "Files to delete",
  EXPORT_SUMMARY_TO_SKIP: "Files to skip",
  EXPORT_SUMMARY_TO_UPDATE: "Files to update",
  EXPORT_WARNING_NO_RECOMMENDED_PATH: "Some files have no recommended destination and were skipped",
  EXPORT_WARNING_PRESET_MISMATCH: "Preset does not match current library state",
  EXPORT_WARNING_SOURCE_MISSING: "Source file not found on disk",
  EXPORT_WARNING_TARGET_NOT_FOUND: "Target directory does not exist",
  EXTENSIONFLAG3_SET: "extensionFlag3 set",
  EXT_HOOK_IS_NOT_CALLABLE: "`ext_hook` is not callable",
  FAILED: "failed",
  FAILED_TO_BUILD_ONE_OR_MORE_WHEELS: "Failed to build one or more wheels",
  FAILED_TO_CONNECT_TO_SOCKS_PROXY: "failed to connect to SOCKS proxy",
  FAILED_TO_CREATE_DIRECTORY: "Failed to create directory",
  FAILED_TO_SIMPLIFY_THE_JSON_SCHEMA_DEFINITIONS: "Failed to simplify the JSON schema definitions",
  FDS_MUST_NOT_BE_EMPTY: "fds must not be empty",
  FIELD_IS_COMPILATION: "Part of compilation",
  FIFO_NOT_SUPPORTED_BY_SYSTEM: "fifo not supported by system",
  FILEOBJ_NOT_PROVIDED_FOR_NON_ZEROSIZE_REGULAR_FILE: "fileobj not provided for non zero-size regular file",
  FILES_COUNT: "files",
  FILES_MARKED_FOR_DELETION: "files marked for deletion",
  FILES_MUST_BE_PROVIDED: "Files must be provided.",
  FILE_HAS_NO_EXISTING_ID3_TAG: "File has no existing ID3 tag",
  FILE_IS_NOT_A_VALID_VORBIS_COMMENT: "file is not a valid Vorbis comment",
  FILE_LIKEREAD_MUST_BE_CALLABLE: "`file_like.read` must be callable",
  FILE_NOT_FOUND: "File not found",
  FINAL: "final",
  FINITE_NUMBER: "finite_number",
  FIRST_PACKET_IS_CONTINUED: "first packet is continued",
  FIRST_TWO_VALUES_NOT_OPTIONAL: "First two values not optional",
  FOO: " /foo",
  FOOBAR: "/foo/bar",
  FOOBARBAZ: "foo/bar/baz",
  FOOBARBAZEGG: "/foo/bar/baz/egg",
  FOOBARBAZEGGPY: "/foo/bar/baz/egg.py",
  FOOBARBAZEGGPY_WORD: "/foo/bar/baz/egg.py word",
  FOOBARBAZEGGPY_WORD_2: " /foo/bar/baz/egg.py word",
  FOOBARBAZFOOBAREGGEGGBAZ: "/foo/bar/baz?foo=bar+egg&egg=baz",
  FOOBARBAZ_2: "/foo/bar/baz/",
  FOOBAR_NOT_FOUND_IN_A: "\"foobar\" not found in a",
  FOO_2: "/foo/",
  FOO_3: "foo",
  FOO_FOOBARBAZEGGPY_WORD: "foo /foo/bar/baz/egg.py word",
  FOO_FOOBARBA_ZEGGPY_WORD: "foo /foo/bar/ba._++z/egg+.py word",
  FORMAT_SHOULD_BE_FILELINECOLUMNEND_LINEEND_COLUMN: "Format should be file:line:column[:end_line:end_column]",
  FOUND_AUDIO_FILES: "Found audio files",
  FOUND_MULTIPLE_HOST_HEADERS: "Found multiple Host: headers",
  FOUND_WHEEL_BUILT_MARKER_BUT_NO_WHL_FILES: "Found wheel built marker, but no .whl files",
  FRACTION_PARSING_INPUT_IS_NOT_A_VALID_FRACTION: "fraction_parsing', 'Input is not a valid fraction",
  FRAGMENTED_CONTROL_FRAME: "fragmented control frame",
  FRAMEB_MUST_BE_8_OR_16: "frame.b must be 8 or 16",
  FRAME_OBJECTS_ARE_UNHASHABLE: "Frame objects are unhashable",
  FRAMING_BIT_WAS_UNSET: "framing bit was unset",
  FRN_OR_FRD_IS_EQUAL_TO_ZERO: "FRN or FRD is equal to zero",
  FUNCTION_DOES_NOT_TYPECHECK: "Function does not typecheck.",
  FUNCTION_HAS_NOT_YET_COMPLETED: "Function has not yet completed",
  GENERATED_IRN: "Generated IR:\n",
  GENRES_CLEANUP_APPLY_HELP: "Apply destructive changes (otherwise preview only)",
  GENRES_CLEANUP_HELP: "Inspect or purge empty (unused) genres",
  GENRES_CLEANUP_LIST_HELP: "List genres with no files assigned",
  GENRES_CLEANUP_PURGE_HELP: "Delete genres with no files assigned",
  GENRES_CMD_HELP: "Manage and inspect genres",
  GENRES_COUNT: "genres",
  GENRES_DISCOVERED: "Genre discovery completed",
  GENRES_DISCOVERED_SUMMARY: "Genre discovery summary",
  GENRES_DISCOVER_CLEAR_HELP: "Clear existing genre mappings before discovery",
  GENRES_DISCOVER_DRY_RUN_HELP: "Preview changes without modifying the database",
  GENRES_DISCOVER_HELP: "Discover genres from file metadata and populate canonical tables",
  GENRES_LIST_HELP: "List canonical genres (supports wildcards *, ?)",
  GENRES_LIST_PATTERN_HELP: "Wildcard pattern (e.g. '*metal*')",
  GENRES_NORMALIZED: "Genres normalized",
  GENRES_NORMALIZE_APPLY_HELP: "Apply changes to the database (otherwise preview only)",
  GENRES_NORMALIZE_CLEAR_HELP: "Replace existing genres instead of appending",
  GENRES_NORMALIZE_HELP: "Normalize multiple genres into a canonical one",
  GENRES_NORMALIZE_SOURCES_HELP: "Exact genre names to normalize (no wildcards)",
  GENRES_NORMALIZE_TARGET_HELP: "Target canonical genre name",
  GENRES_SEARCH_PLACEHOLDER: "Search genres…",
  GENRE_DISCOVERY_COMPLETE: "Genre discovery completed",
  GETOPT_HASNT_BEEN_CALLED_YET: "'getopt()' hasn't been called yet",
  GET_OR_GET_ITER_IS_ALREADY_RUNNING: "get() or get_iter() is already running",
  GOT_DATA_WHEN_EXPECTING_EOF: "Got data when expecting EOF",
  GOT_UNKNOWN_FILE_TYPE: "Got unknown file type",
  GZIP_MODULE_IS_NOT_AVAILABLE: "gzip module is not available",
  HASH_VALUES_MUST_BE_STRINGS: "Hash values must be strings",
  HEADER_SIZE_NOT_SYNCHSAFE: "Header size not synchsafe",
  HELLO: "hello",
  HELLO_WORLD: "Hello, **World**",
  HELLO_WORLD_2: "Hello world!",
  HELLO_WORLD_3: "hello world",
  HELLO_WORLD_4: "hello world!",
  HIGH_MUST_BE_GREATER_THAN_OR_EQUAL_TO_LOW: "high must be greater than or equal to low",
  HINT_SEE_ALSO_DEBUGGING_SEGFAULTS_IN_MYPYCDOCDEVINTROMD: "hint: See also \"Debugging Segfaults\" in mypyc/doc/dev-intro.md",
  HINT_YOU_MAY_NEED_TO_BUILD_A_DEBUG_VERSION_OF_PYTHON_FIRST_AND_USE_IT: "hint: You may need to build a debug version of Python first and use it",
  HOME_PREFIX: "--home\", \"--prefix",
  HTTPRESPONSE_HAS_NO_FILE_TO_GET_A_FILENO_FROM: "HTTPResponse has no file to get a fileno from",
  HTTPSEXAMPLEORGFOOBARHEADER: "https://example.org?foo=bar#header",
  IDNA_2008_DOES_NOT_UTILISE_NAMEPREP_PROTOCOL: "IDNA 2008 does not utilise nameprep protocol",
  IFF_CHUNK_ID_MUST_BE_FOUR_ASCII_CHARACTERS: "IFF chunk ID must be four ASCII characters.",
  ILLEGAL_REQUEST_LINE: "illegal request line",
  INCLUDE_DIRS_IF_SUPPLIED_MUST_BE_A_LIST_OF_STRINGS: "'include_dirs' (if supplied) must be a list of strings",
  INCOMPLETE_FRAGMENTED_MESSAGE: "incomplete fragmented message",
  INCONSISTENT_HIERARCHY_NO_C3_MRO_IS_POSSIBLE: "Inconsistent hierarchy, no C3 MRO is possible",
  INCORRECT_MASKING: "incorrect masking",
  INDENT_WIDTH_MUST_BE_NONNEGATIVE: "Indent width must be non-negative",
  INFILES_MUST_BE_A_STRING_OR_A_LIST_OR_TUPLE_OF_STRINGS: "'infiles' must be a string, or a list or tuple of strings",
  INF_AND_NAN_NOT_SUPPORTED: "inf and nan not supported",
  INITIAL_VALUE_MUST_BE_0: "initial_value must be >= 0",
  INITIAL_VALUE_MUST_BE_AN_INTEGER: "initial_value must be an integer",
  INITVAR_OBJECT_IS_NOT_CALLABLE: "'InitVar' object is not callable",
  INIT_VAR: "init_var",
  INPUT_IMAGE_MUST_BE_IN_SPIDER_FORMAT: "input image must be in Spider format",
  INSTALLING_MISSING_STUB_PACKAGES: "Installing missing stub packages:",
  INTEGER_VALUE_OUT_OF_RANGE: "Integer value out of range",
  INTERNAL_ERROR: "Internal Error.",
  INTERRUPTED: "interrupted",
  INVALID_ACTION_SKIPPED: "Skipping row {id}: invalid action '{action}'",
  INVALID_ALABEL: "Invalid A-label",
  INVALID_ARGUMENT: "Invalid argument",
  INVALID_ARGUMENT_FOR_PYGMENTSDOC_DIRECTIVE: "invalid argument for \"pygmentsdoc\" directive",
  INVALID_ASCII_IN_ALABEL: "Invalid ASCII in A-label",
  INVALID_ATOM: "Invalid atom",
  INVALID_BOOL: "invalid bool",
  INVALID_CHARACTERS_FOR_QUOTEDSTRING_ENCODING: "invalid characters for quoted-string encoding",
  INVALID_CHARACTER_IN_BUILD_TAG: "invalid character ('-') in build tag",
  INVALID_CODEC_ENTRY: "invalid codec entry",
  INVALID_COMPRESSED_DATA: "invalid compressed data",
  INVALID_CUESHEET_OBJECT_TYPE: "Invalid cuesheet object type!",
  INVALID_DB_MODE: "INVALID_DB_MODE",
  INVALID_DESCRIPTOR_LENGTH: "invalid descriptor length",
  INVALID_EVENT: "invalid event",
  INVALID_EXTENDED_HEADER_SIZE: "invalid extended header size",
  INVALID_FIELD_PROPERTY_ENTRY: "invalid field property entry",
  INVALID_FORMAT: "invalid format",
  INVALID_FRAME_ID: "Invalid frame ID",
  INVALID_FRAME_KEY: "Invalid frame key.",
  INVALID_GENRE: "invalid genre",
  INVALID_HEADER: "invalid header",
  INVALID_HEADER_SIZE: "invalid header size",
  INVALID_HTTP_HEADER_NAME: "Invalid HTTP header name.",
  INVALID_HTTP_HEADER_VALUE: "Invalid HTTP header value.",
  INVALID_IFF_KEY: "Invalid IFF key.",
  INVALID_KEYWORD_ARGUMENTS_TO_PRINT: "invalid keyword arguments to print()",
  INVALID_MVHD: "Invalid mvhd",
  INVALID_OBJECT_SIZE: "invalid object size",
  INVALID_OPCODE: "invalid opcode",
  INVALID_OPTION: "Invalid option",
  INVALID_PACKET_SIZE: "Invalid packet size.",
  INVALID_PADDING: "invalid padding",
  INVALID_RG_PACKET_SIZE: "Invalid RG packet size.",
  INVALID_SAMPLE_RATE: "Invalid sample rate",
  INVALID_SEEKTABLE_OBJECT_TYPE: "Invalid seektable object type!",
  INVALID_SIZE_IN_HEADER_EXTENSION: "invalid size in header extension",
  INVALID_STATUS_CODE: "invalid status code",
  INVALID_STATUS_FILE_NOT_A_DICT: "Invalid status file (not a dict)",
  INVALID_STATUS_FILE_NO_CONNECTION_NAME_FIELD: "Invalid status file (no connection_name field)",
  INVALID_STATUS_FILE_NO_PID_FIELD: "Invalid status file (no pid field)",
  INVALID_STSD: "Invalid stsd",
  INVALID_SYNC: "invalid sync",
  INVALID_SYNCSAFE_STRING: "invalid sync-safe string",
  INVALID_SYSCONFIGGET_CONFIG_VAREXT_SUFFIX: "invalid sysconfig.get_config_var('EXT_SUFFIX')",
  INVALID_TOC_ENTRY_SIZE: "Invalid TOC entry size",
  INVALID_TRASH_ROOT: "INVALID_TRASH_ROOT",
  INVALID_TYPE_EXPECTED_TIMEDELTA_STRING_BYTES_INT_OR_FLOAT: "invalid type; expected timedelta, string, bytes, int or float",
  INVALID_VALIDATION_ALIAS_TYPE_IT_SHOULD_BE_STR_ALIASCHOICES_OR_ALIASPATH: "Invalid `validation_alias` type. it should be `str`, `AliasChoices`, or `AliasPath`",
  INVALID_VERSION_TOO_LONG: "Invalid version: too long",
  IPYWIDGETS: "ipywidgets",
  IP_ANY_ADDRESS_VALUE_IS_NOT_A_VALID_IPV4_OR_IPV6_ADDRESS: "ip_any_address', 'value is not a valid IPv4 or IPv6 address",
  IP_ANY_INTERFACE_VALUE_IS_NOT_A_VALID_IPV4_OR_IPV6_INTERFACE: "ip_any_interface', 'value is not a valid IPv4 or IPv6 interface",
  IP_ANY_NETWORK_VALUE_IS_NOT_A_VALID_IPV4_OR_IPV6_NETWORK: "ip_any_network', 'value is not a valid IPv4 or IPv6 network",
  IP_V4_ADDRESS_INPUT_IS_NOT_A_VALID_IPV4_ADDRESS: "ip_v4_address', 'Input is not a valid IPv4 address",
  IP_V4_INTERFACE_INPUT_IS_NOT_A_VALID_IPV4_INTERFACE: "ip_v4_interface', 'Input is not a valid IPv4 interface",
  IP_V4_NETWORK_INPUT_IS_NOT_A_VALID_IPV4_NETWORK: "ip_v4_network', 'Input is not a valid IPv4 network",
  IP_V6_ADDRESS_INPUT_IS_NOT_A_VALID_IPV6_ADDRESS: "ip_v6_address', 'Input is not a valid IPv6 address",
  IP_V6_INTERFACE_INPUT_IS_NOT_A_VALID_IPV6_INTERFACE: "ip_v6_interface', 'Input is not a valid IPv6 interface",
  IP_V6_NETWORK_INPUT_IS_NOT_A_VALID_IPV6_NETWORK: "ip_v6_network', 'Input is not a valid IPv6 network",
  ISLICE_EXTENDED__GETITEM___ARGUMENT_MUST_BE_A_SLICE: "islice_extended.__getitem__ argument must be a slice",
  ISSUBCLASS_ARG_1_MUST_BE_A_CLASS: "issubclass() arg 1 must be a class",
  IS_NEITHER_COMPLEX_FLOAT_OR_INT: "is neither complex, float or int",
  IS_NEITHER_FLOAT_OR_INT: "is neither float or int",
  IS_NOT_AN_EMPTY_TUPLE: "is not an empty tuple",
  IS_NOT_AN_IO_OBJECT: "is not an I/O object",
  IS_NOT_A_BINARY_IO_OBJECT: "is not a binary I/O object",
  IS_NOT_A_CLASS: "is not a class",
  IS_NOT_A_DICT: "is not a dict",
  IS_NOT_A_FROZENSET: "is not a frozenset",
  IS_NOT_A_LIST: "is not a list",
  IS_NOT_A_MAPPING: "is not a mapping",
  IS_NOT_A_MUTABLE_MAPPING: "is not a mutable mapping",
  IS_NOT_A_SEQUENCE: "is not a sequence",
  IS_NOT_A_SET: "is not a set",
  IS_NOT_A_TEXT_BASED_IO_OBJECT: "is not a text based I/O object",
  IS_NOT_A_TUPLE: "is not a tuple",
  IS_NOT_BYTESLIKE: "is not bytes-like",
  IS_NOT_CALLABLE: "is not callable",
  IS_NOT_NONE: "is not None",
  ITALIC_CYANITALIC_CYAN: "[italic cyan]italic cyan!",
  ITEMS_SELECTED: "items selected",
  ITEM_IN_LIST_NOT_STR: "item in list not str",
  ITEM_SIZE_EXCEEDS_MAXIMUM_SIZE: "item size exceeds maximum size",
  ITERABLE_IS_NOT_DIVISIBLE_BY_N: "iterable is not divisible by n.",
  ITERABLE_MUST_CONTAIN_BYTES_OR_STR: "iterable must contain bytes or str",
  ITERABLE_MUST_CONTAIN_UNIFORM_TYPES: "iterable must contain uniform types",
  ITERABLE_OR_LENGTH_IS_REQUIRED: "iterable or length is required",
  ITS_AN_INT: "It's an int",
  ITS_A_STR: "It's a str",
  I_ONLY_SEND_HTTP11: "I only send HTTP/1.1",
  JUST_TO_CHECK_IF_THE_COMMAND_RUNS: "just to check if the command runs",
  KEEP_MUST_BE_AN_INTEGER: "--keep must be an integer",
  KEYVALUE_PAIRS_MAY_NOT_OVERLAP: "Key/Value pairs may not overlap",
  KEY_CANNOT_MAP_TO_ITSELF: "Key cannot map to itself",
  KEY_CONFLICT_IN_INVERTED_MAPPING: "Key conflict in inverted mapping",
  KEY_HAS_TO_BE_STR: "key has to be str",
  KINDS: "  ** kinds **",
  KIND_MUST_BE_TEXT_BINARY_OR_EXTERNAL: "kind must be TEXT, BINARY, or EXTERNAL",
  LABEL_BEGINS_WITH_AN_ILLEGAL_COMBINING_CHARACTER: "Label begins with an illegal combining character",
  LABEL_ENDS_WITH_ILLEGAL_CODEPOINT_DIRECTIONALITY: "Label ends with illegal codepoint directionality",
  LABEL_HAS_DISALLOWED_HYPHENS_IN_3RD_AND_4TH_POSITION: "Label has disallowed hyphens in 3rd and 4th position",
  LABEL_MUST_BE_IN_NORMALIZATION_FORM_C: "Label must be in Normalization Form C",
  LABEL_MUST_NOT_START_OR_END_WITH_A_HYPHEN: "Label must not start or end with a hyphen",
  LABEL_TOO_LONG: "Label too long",
  LANDING_CHECKING_ENV: "Checking environment...",
  LANDING_DIRECT_DISABLED_HINT: "No active database configured",
  LANDING_ENTER_DIRECT: "Enter directly",
  LANDING_ENTER_WIZARD: "Enter startup wizard",
  LANDING_NO_DB_HINT: "No active database found. Please run the wizard first.",
  LANDING_SUBTITLE: "A personal music library manager",
  LANDING_TITLE: "Pedro Organiza",
  LANDING_USING_DB: "Using existing database",
  LAST_PACKET_DOES_NOT_COMPLETE: "last packet does not complete",
  LEVEL_MUST_BE_HEAD_ROW_OR_FOOT: "level must be 'head', 'row' or 'foot'",
  LIBRARIES_IF_SUPPLIED_MUST_BE_A_LIST_OF_STRINGS: "'libraries' (if supplied) must be a list of strings",
  LIBRARIES_OPTION_MUST_BE_A_LIST_OF_TUPLES: "'libraries' option must be a list of tuples",
  LIBRARY_DIRS_IF_SUPPLIED_MUST_BE_A_LIST_OF_STRINGS: "'library_dirs' (if supplied) must be a list of strings",
  LIB_NOT_FOUND: "Library directory not found",
  LIMIT_SECONDS_MUST_BE_POSITIVE: "limit_seconds must be positive",
  LINE_TOO_LONG: "line too long",
  LINE_WITHOUT_CRLF: "line without CRLF",
  LINKNAME_IS_TOO_LONG: "linkname is too long",
  LIST_HOOK_IS_NOT_CALLABLE: "`list_hook` is not callable",
  LOADING: "Loading...",
  LOCALNS_ARGUMENTS_ARE_NOT_LONGER_ACCEPTED: "`localns` arguments are not longer accepted.",
  LOCATION: "Location",
  LOOK_AT_THE_TITLE_OF_YOUR_TERMINAL_WINDOW: "Look at the title of your terminal window ^",
  LOW_MUST_BE_POSITIVE_OR_EQUAL_TO_ZERO: "low must be positive or equal to zero",
  LZMA_MODULE_IS_NOT_AVAILABLE: "lzma module is not available",
  MACROS_IF_SUPPLIED_MUST_BE_A_LIST_OF_TUPLES: "'macros' (if supplied) must be a list of tuples",
  MAKE_TEST_C_UNIT_TEST_FAILURE: "make test: C unit test failure",
  MALFORMED_ALABEL_NO_PUNYCODE_ELIGIBLE_CONTENT_FOUND: "Malformed A-label, no Punycode eligible content found",
  MALFORMED_JSON_DATA_RECEIVED: "Malformed JSON data received.",
  MALFORMED_STATUS_FILE_NOT_JSON: "Malformed status file (not JSON)",
  MASK_MUST_CONTAIN_4_BYTES: "mask must contain 4 bytes",
  MAXFDS_MUST_BE_A_POSITIVE_INTEGER: "maxfds must be a positive integer",
  MAXIMUM_SIZE_MUST_BE_GREATER_THAN_ZERO: "maximum size must be greater than zero",
  MAX_BUFFER_SIZE_CANNOT_BE_NEGATIVE: "max_buffer_size cannot be negative",
  MAX_BUFFER_SIZE_MUST_BE_EITHER_AN_INTEGER_OR_MATHINF: "max_buffer_size must be either an integer or math.inf",
  MAX_MIN_END: "max, min: \", end=\" ",
  MAX_VALUE_MUST_BE_AN_INTEGER_OR_NONE: "max_value must be an integer or None",
  MEMORYVIEW_IS_TOO_LARGE: "Memoryview is too large",
  MESSAGE_MUST_NOT_BE_EMPTY: "message must not be empty",
  METADATA_CANNOT_CONTAIN_NONE: "metadata cannot contain None",
  MISMATCHING_NUMBER_OF_ITERABLES_AND_LENGTHS: "Mismatching number of iterables and lengths.",
  MISSING_BOUNDARY_IN_MULTIPART: "Missing boundary in multipart.",
  MISSING_DEPENDENCIES_FOR_SOCKS_SUPPORT: "Missing dependencies for SOCKS support.",
  MISSING_FILENAME_OR_FILEOBJ_ARGUMENT: "Missing filename or fileobj argument",
  MISSING_MANDATORY_HOST_HEADER: "Missing mandatory Host: header",
  MISSING_METADATAVERSION: "Missing Metadata-Version",
  MISSING_METADATA_PACKET: "Missing metadata packet",
  MISSING_PATH_ARGUMENT: "missing path argument",
  MISSING_RECOMMENDED_PATH: "MISSING_RECOMMENDED_PATH",
  MISSING_REQUIRED_ARGUMENT_SEARCH_QUERY: "Missing required argument (search query).",
  MISSING_STREAM_INFO: "missing stream info",
  MISSING_SUBPROTOCOL: "missing subprotocol",
  MODEL_JSON_SCHEMA_MUST_BE_CALLED_ON_A_SUBCLASS_OF_BASEMODEL_NOT_BASEMODEL_ITSELF: "model_json_schema() must be called on a subclass of BaseModel, not BaseModel itself.",
  MODE_MUST_BE_R_A_W_OR_X: "mode must be 'r', 'a', 'w' or 'x'",
  MODE_MUST_BE_R_OR_W: "mode must be 'r' or 'w'",
  MODE_MUST_BE_R_W_OR_X: "mode must be 'r', 'w' or 'x'",
  MSGLEN_MUST_BE_A_NONNEGATIVE_INTEGER: "msglen must be a non-negative integer",
  MUSIC_DB_NOT_SET: "MUSIC_DB_NOT_SET",
  MUST_APPEAR_ALONE_IN_A_PATH_SEGMENT: "** must appear alone in a path segment",
  MUST_SPECIFY_AT_LEAST_ONE_OF_READTRUE_WRITETRUE: "must specify at least one of read=True, write=True",
  MUST_SPECIFY_COMMAND_AND_OPTION: "Must specify --command *and* --option",
  MUST_SPECIFY_NUMBER_OF_FILES_TO_KEEP: "Must specify number of files to keep",
  MUST_SPECIFY_SETVALUE_OR_REMOVE: "Must specify --set-value or --remove",
  MYPKGOTHER_NOT_DEFINED: "mypkg.other not defined",
  MYPY_BUG_UNPACK_SHOULD_BE_HANDLED_AT_A_HIGHER_LEVEL: "Mypy bug: unpack should be handled at a higher level.",
  N: "\n",
  NAME_IS_REQUIRED_WITH_PROMPTTRUE: "'name' is required with 'prompt=True'.",
  NAME_IS_TOO_LONG: "name is too long",
  NAME_MUST_BE_A_STRING: "'name' must be a string",
  NAME_PREFIX_OR_DATA: "\" + (name_prefix or \"data",
  NANOSECONDS_MUST_BE_AN_INTEGER: "nanoseconds must be an integer",
  NANOSECONDS_MUST_BE_A_NONNEGATIVE_INTEGER_LESS_THAN_999999999: "nanoseconds must be a non-negative integer less than 999999999.",
  NARGS1_IS_NOT_SUPPORTED_FOR_OPTIONS: "nargs=-1 is not supported for options.",
  NARROW_REQUIREMENT_SELECTION_RETURNED_0_NAMES: "narrow_requirement_selection returned 0 names",
  NCONSIDER_THE_FOLLOWING_CODEN: "\nConsider the following code:\n",
  NDELETING_TO_THE_START_OF_THE_LINE: "\n...Deleting to the start of the line...",
  NDIMRESETN_TBSTRIPN: "\n{dim}{}{reset}\n', tb.strip('\n",
  NEEDED_A_SPECIFIC_FILE_TO_BE_MODIFYING: "Needed a specific file to be modifying.",
  NEEDS_TO_BE_STR_NOT_BYTES: "needs to be str not bytes",
  NERROR_REPORTN: "\nError report:\n",
  NFAILFAST_STOPPING_ON_FIRST_FAILURE: "\n[FAIL-FAST] Stopping on first failure.",
  NNAND_TO_THE_END_OF_THE_LINE: "\n\n...And to the end of the line...",
  NNNOW_THE_WHOLE_LINE_WILL_BE_ERASED: "\n\n...Now the whole line will be erased...",
  NO: "no",
  NONOPTIMIZED: "non-optimized",
  NONZERO_FLAGS_NOT_ALLOWED_IN_CALLS_TO_RECV: "non-zero flags not allowed in calls to recv",
  NONZERO_FLAGS_NOT_ALLOWED_IN_CALLS_TO_RECV_INTO: "non-zero flags not allowed in calls to recv_into",
  NONZERO_FLAGS_NOT_ALLOWED_IN_CALLS_TO_SEND: "non-zero flags not allowed in calls to send",
  NONZERO_FLAGS_NOT_ALLOWED_IN_CALLS_TO_SENDALL: "non-zero flags not allowed in calls to sendall",
  NORMALIZE_GENRES: "Normalize genres",
  NOTE_RUN_MYPY_AGAIN_FOR_UPTODATE_RESULTS_WITH_INSTALLED_TYPES: "note: Run mypy again for up-to-date results with installed types",
  NOTE_SAVED: "Note saved",
  NOTHING_TO_OPEN: "nothing to open",
  NOT_AN_ASF_FILE: "Not an ASF file.",
  NOT_AN_LZMA_FILE: "not an lzma file",
  NOT_AN_OPTIMFROG_FILE: "not an OptimFROG file",
  NOT_ASCII: "not ascii",
  NOT_A_AC3_FILE: "not a AC3 file",
  NOT_A_BZIP2_FILE: "not a bzip2 file",
  NOT_A_GZIP_FILE: "not a gzip file",
  NOT_A_LAME_HEADER: "Not a lame header",
  NOT_A_MIDI_FILE: "Not a MIDI file",
  NOT_A_MONKEYS_AUDIO_FILE: "not a Monkey's Audio file",
  NOT_A_MP4_FILE: "not a MP4 file",
  NOT_A_MUSEPACK_FILE: "not a Musepack file",
  NOT_A_STR: "not a str",
  NOT_A_TAK_FILE: "not a TAK file",
  NOT_A_VBRI_HEADER: "Not a VBRI header",
  NOT_A_WAVPACK_FILE: "not a WavPack file",
  NOT_A_XING_HEADER: "Not a Xing header",
  NOT_CACHED: "Not cached :(",
  NOT_ENOUGH_DATA: "Not enough data",
  NOT_ENOUGH_DATA_2: "not enough data",
  NOT_ENOUGH_DATA_IN_CHNL_CHUNK: "Not enough data in CHNL chunk",
  NOT_ENOUGH_DATA_IN_CMPR_CHUNK: "Not enough data in CMPR chunk",
  NOT_ENOUGH_DATA_IN_FRTE_CHUNK: "Not enough data in FRTE chunk",
  NOT_ENOUGH_DATA_IN_FS_CHUNK: "Not enough data in FS chunk",
  NOT_ENOUGH_FRAME_DATA: "not enough frame data",
  NOT_IMPLEMENTED: "Not implemented",
  NOT_IN_RANGE: "not in range",
  NOT_NULL_TERMINATED: "not null terminated",
  NOT_REQUIRED: "not_required",
  NOT_SUPPORTED: "Not supported",
  NOT_SUPPORTED_TIMING_INTERVAL: "Not supported timing interval",
  NOT_SURE_WHAT_TO_DO_WITH_AN_INCREF_OF_A_SPILL: "not sure what to do with an incref of a spill...",
  NOT_WINDOWS: "Not windows",
  NO_ACTIONS_IMPORTED: "No actions were imported",
  NO_ACTIVE_DB: "NO_ACTIVE_DB",
  NO_ACTIVE_MUSIC_DATABASE_SET_API_WILL_REJECT_REQUESTS: "⚠️ No active music database set. API will reject requests.",
  NO_ANNOTATION_WITHOUT_ERRORS: "No annotation without errors",
  NO_APE_TAG_FOUND: "No APE tag found",
  NO_COMMANDS_SUPPLIED: "no commands supplied",
  NO_DATA_LEFT: "no data left",
  NO_DATA_RECEIVED: "No data received",
  NO_DISTINFO_FOLDER_FOUND_IN_WHEEL: "No .dist-info folder found in wheel",
  NO_ERRORS_REPORTED: "No errors reported",
  NO_EXTENSIONS_SUPPORTED: "no extensions supported",
  NO_FILES_TO_REVIEW: "No files to review",
  NO_GUESSES_THAT_MATCH_CRITERIA: "No guesses that match criteria!",
  NO_HOST_SPECIFIED: "No host specified.",
  NO_ID3_CHUNK: "No ID3 chunk",
  NO_KEYS_FOUND_IN_THE_FIRST_MAPPING: "No keys found in the first mapping.",
  NO_LEXER_MATCHING_THE_TEXT_FOUND: "no lexer matching the text found",
  NO_METADATA_EXCEPT_PKGINFO_IS_AVAILABLE: "No metadata except PKG-INFO is available",
  NO_MODULE_NAMED__YAML: "No module named '_yaml'",
  NO_NAMED_COLOR_FOUND_USE_FALLBACKTRUE_AS_HEX_OR_AS_RGB: "no named color found, use fallback=True, as_hex() or as_rgb()",
  NO_PIVOT_FOUND: "No pivot found",
  NO_REQUEST_LINE_RECEIVED: "no request line received",
  NO_RESPONSE_LINE_RECEIVED: "no response line received",
  NO_RESPONSE_RETURNED: "No response returned.",
  NO_RESULTS: "No files match the current filters",
  NO_SELECTEQUIVALENT_AVAILABLE: "no select-equivalent available",
  NO_SETUPCFG: "~~~~~ **NO** setup.cfg ~~~~~",
  NO_STATUS_FILE_FOUND: "No status file found",
  NO_SUBPROTOCOLS_SUPPORTED: "no subprotocols supported",
  NO_SUCH_GROUP: "No such group",
  NTYPE_CHECKING_REPORTN: "\nType checking report:\n",
  NUMBER_OF_ITERABLES_AND_OFFSETS_DIDNT_MATCH: "Number of iterables and offsets didn't match",
  NUMERIC_RANGE_ARG_3_MUST_NOT_BE_ZERO: "numeric_range() arg 3 must not be zero",
  NUMERIC_RANGE_OBJECT_INDEX_OUT_OF_RANGE: "numeric range object index out of range",
  N_ALL_TESTS_PASSED: "\n✅ All tests passed.",
  N_APP_DIRS_WITHOUT_OPTIONAL_APPAUTHOR: "\n-- app dirs (without optional 'appauthor')",
  N_APP_DIRS_WITHOUT_OPTIONAL_VERSION: "\n-- app dirs (without optional 'version')",
  N_APP_DIRS_WITH_DISABLED_APPAUTHOR: "\n-- app dirs (with disabled 'appauthor')",
  N_EXPORT_PREVIEW: "\n📦 Export Preview",
  N_MUST_BE_0: "n must be > 0",
  N_MUST_BE_0_2: "n must be >= 0",
  N_MUST_BE_AT_LEAST_1: "n must be at least 1",
  N_MUST_BE_AT_LEAST_ONE: "n must be at least one",
  N_MUST_BE_GREATER_THAN_0: "n must be greater than 0",
  N_MUST_BE_LENSEQ: "n must be <= len(seq)",
  N_MUST_NOT_BE_NONE_WHEN_USING_STRICT_MODE: "n must not be None when using strict mode.",
  OBJECTS_MUST_BE_A_LIST_OR_TUPLE_OF_STRINGS: "'objects' must be a list or tuple of strings",
  OBJECT_HOOK_IS_NOT_CALLABLE: "`object_hook` is not callable",
  OBJECT_PAIRS_HOOK_AND_OBJECT_HOOK_ARE_MUTUALLY_EXCLUSIVE: "object_pairs_hook and object_hook are mutually exclusive",
  OBJECT_PAIRS_HOOK_IS_NOT_CALLABLE: "`object_pairs_hook` is not callable",
  OK: "ok",
  OK_2: "OK",
  ONLY_3_AND_4_POSSIBLE_FOR_V2_VERSION: "Only 3 and 4 possible for v2_version",
  ONLY_3_OR_4_ALLOWED_FOR_V2_VERSION: "Only 3 or 4 allowed for v2_version",
  ONLY_BLOCKING_SOCKETS_ARE_SUPPORTED: "only blocking sockets are supported",
  ONLY_COMPRESSED_OUTGOING_FRAMES_USE_MEMORYVIEW: "only compressed outgoing frames use memoryview",
  ONLY_GENERIC_TYPE_ALIASES_ARE_SUBSCRIPTABLE: "Only generic type aliases are subscriptable",
  ONLY_MACOS_IS_SUPPORTED: "Only macOS is supported",
  ONLY_ONE_OF_STDIN_AND_INPUT_IS_ALLOWED: "only one of stdin and input is allowed",
  ONLY_ONE_TRACK_ID_MAY_BE_SET_PER_SONG: "only one track ID may be set per song",
  ONLY_STR_OR_TEXT_CAN_BE_APPENDED_TO_TEXT: "Only str or Text can be appended to Text",
  ONLY_SUPPORT_BYTES_RANGE: "Only support bytes range",
  ON_BLUEHELLO_JUSTIFYRIGHT: "[on blue]Hello\", justify=\"right",
  ON_REDON_RED: "[on red]on red!",
  OPTIMIZE_MUST_BE_0_1_OR_2: "optimize must be 0, 1, or 2",
  OPTIONS_AFTER_PARSING_COMMAND_LINE: "options (after parsing command line):",
  OPTIONS_AFTER_PARSING_CONFIG_FILES: "options (after parsing config files):",
  OPTIONS_OUTDATED_AND_UPTODATE_CANNOT_BE_COMBINED: "Options --outdated and --uptodate cannot be combined.",
  ORIGIN_MULTIPLE_VALUES: "Origin\", \"multiple values",
  OSMKDIR_NOT_SUPPORTED_ON_THIS_PLATFORM: "\"os.mkdir\" not supported on this platform.",
  OUTPUT_DIR_MUST_BE_A_STRING_OR_NONE: "'output_dir' must be a string or None",
  OUT_OF_RANGE: "Out of range",
  OUT_OF_RANGE_2: "out of range",
  OVERFLOW_IN_NUMBER_FIELD: "overflow in number field",
  OVERRIDE_IN_SUBCLASS: "Override in subclass",
  O_HAI: "o hai",
  PAGE_HAS_NOT_PACKETS: "page has not packets",
  PARALLEL_SHOULD_BE_AN_INTEGER: "parallel should be an integer",
  PARAMETERS_SHOULD_HAVE_BEEN_BOUND_TO_A_CLASS: "Parameters should have been bound to a class",
  PARAMSPEC_LITERALS_CANNOT_HAVE_UNBOUND_TYPEVARS: "ParamSpec literals cannot have unbound TypeVars",
  PARENT_DOES_NOT_EXIST_PARENT_DIRECTORY_DOES_NOT_EXIST: "parent_does_not_exist', 'Parent directory does not exist",
  PARSE_FLOAT_MUST_NOT_RETURN_DICTS_OR_LISTS: "parse_float must not return dicts or lists",
  PARSE_SHOULDNT_STEP_AFTER_ERROR: "parse() shouldn't step after error",
  PARTITIONED_COOKIES_ARE_ONLY_SUPPORTED_IN_PYTHON_314_AND_ABOVE: "Partitioned cookies are only supported in Python 3.14 and above.",
  PATHS_MUST_BE_INSIDE_SOURCE_TREE: "paths must be inside source tree",
  PATHS_MUST_BE_RELATIVE: "paths must be relative",
  PATH_AND_SOCK_ARGUMENTS_ARE_INCOMPATIBLE: "path and sock arguments are incompatible",
  PATH_EXISTS_PATH_ALREADY_EXISTS: "path_exists', 'Path already exists",
  PATH_NOT_DIRECTORY_PATH_DOES_NOT_POINT_TO_A_DIRECTORY: "path_not_directory', 'Path does not point to a directory",
  PATH_NOT_FILE_PATH_DOES_NOT_POINT_TO_A_FILE: "path_not_file', 'Path does not point to a file",
  PATH_NOT_SOCKET_PATH_DOES_NOT_POINT_TO_A_SOCKET: "path_not_socket', 'Path does not point to a socket",
  PATH_OR_URL_MUST_BE_PROVIDED: "path or url must be provided",
  PATH_SEPARATORS_NOT_ALLOWED_IN_SCRIPT_NAMES: "Path separators not allowed in script names",
  PATH_TYPE_INPUT_IS_NOT_A_VALID_PATH: "path_type', 'Input is not a valid path",
  PATH_UPDATED: "Proposed path updated",
  PATTERN_BYTES_TYPE_INPUT_SHOULD_BE_A_BYTES_PATTERN: "pattern_bytes_type', 'Input should be a bytes pattern",
  PATTERN_NORMALIZED_TO_NOTHING: "Pattern normalized to nothing.",
  PATTERN_REGEX_INPUT_SHOULD_BE_A_VALID_REGULAR_EXPRESSION: "pattern_regex', 'Input should be a valid regular expression",
  PATTERN_STR_TYPE_INPUT_SHOULD_BE_A_STRING_PATTERN: "pattern_str_type', 'Input should be a string pattern",
  PATTERN_TYPE_INPUT_SHOULD_BE_A_VALID_PATTERN: "pattern_type', 'Input should be a valid pattern",
  PAYLOAD_IN_AN_INVALID_ENCODING: "payload in an invalid encoding",
  PAYMENT_CARD_NUMBER_DIGITS_CARD_NUMBER_IS_NOT_ALL_DIGITS: "payment_card_number_digits', 'Card number is not all digits",
  PAYMENT_CARD_NUMBER_LUHN_CARD_NUMBER_IS_NOT_LUHN_VALID: "payment_card_number_luhn', 'Card number is not luhn valid",
  PEAK_MUST_BE_0_AND_2: "peak must be => 0 and < 2.",
  PEDRO_DB_OK: "Pedro database detected OK and is ready to use.",
  PEDRO_ORGANIZA: "Pedro Organiza",
  PEDRO_ORGANIZA_TEST_RUNNER: "Pedro Organiza — Test Runner",
  PEER_UNEXPECTEDLY_CLOSED_CONNECTION: "peer unexpectedly closed connection",
  PENDING_CHANGES: "pending changes",
  PERMANENT_DELETE_REQUESTED: "⚠️  PERMANENT DELETE REQUESTED",
  PID_FIELD_IS_NOT_AN_INT: "pid field is not an int",
  PILE_OF_POO_PROMPTINVALIDNUMBER_MUST_BE_BETWEEN_1_AND_10: ":pile_of_poo: [prompt.invalid]Number must be between 1 and 10",
  PIP_INTERNALS_DONT_IMPORT_CRYPTOGRAPHY_ON_WINDOWS: "pip internals: don't import cryptography on Windows",
  PLEASE_CORRECT_YOUR_PACKAGE: "Please correct your package.",
  PLEASE_PIP_INSTALL_SLACKSDK: "Please `pip install slack-sdk`",
  PLEASE_PROVIDE_A_PATTERN: "Please provide a pattern",
  POP_TAKES_AT_MOST_TWO_ARGUMENTS: "pop takes at most two arguments",
  PRECISION: "  ** precision **",
  PRESET_COMING_SOON: "Presets coming soon",
  PRESET_NAME: "Preset name",
  PRESET_SAVED: "Preset saved",
  PRE_CANNOT_BE_USED_WITH_ALLRELEASES_OR_ONLYFINAL: "--pre cannot be used with --all-releases or --only-final.",
  PRINT_ME_IF_YOU_CAN: "Print me if you can",
  PROMPTINVALIDPASSWORD_TOO_SHORT: "[prompt.invalid]password too short",
  PROTOCOLS_CANNOT_BE_INSTANTIATED: "Protocols cannot be instantiated",
  PROVIDE_EITHER_CREDENTIALS_OR_CHECK_CREDENTIALS: "provide either credentials or check_credentials",
  PYDANTIC_PLUGINS_SHOULD_IMPLEMENT_NEW_SCHEMA_VALIDATOR: "Pydantic plugins should implement `new_schema_validator`.",
  PYTHONDOTENV_IS_NOT_INSTALLED_RUN_PIP_INSTALL_PYDANTICDOTENV: "python-dotenv is not installed, run `pip install pydantic[dotenv]`",
  PYTHON_38_OR_LATER_IS_REQUIRED: "Python 3.8 or later is required",
  PYTHON_39_OR_LATER_IS_REQUIRED: "Python 3.9 or later is required",
  RAISE_EXCEPTIONS_REQUIRES_AT_LEAST_PYTHON_311: "raise_exceptions requires at least Python 3.11",
  RANGE_HEADER_RANGE_MUST_BE_REQUESTED: "Range header: range must be requested",
  RANGE_HEADER_START_MUST_BE_LESS_THAN_END: "Range header: start must be less than end",
  RANGE_REQUEST_IS_NOT_SUPPORTED: "range request is not supported",
  RAW_IS_TOO_LARGE: "Raw is too large",
  READFILE_OPERATION_ABORTED: "ReadFile operation aborted.",
  READING_FROM: "reading from",
  READONLY_ATTRIBUTE: "readonly attribute",
  READ_END_OF_STRING: "read: End of string",
  READ_REGEX_PATTERN_NOT_FOUND: "read_regex: Pattern not found",
  READ_SIZE_MUST_BE_SMALLER_THAN_MAX_BUFFER_SIZE: "read_size must be smaller than max_buffer_size",
  RECEIVED_CLOSE_THEN_RECEIVED_MORE_DATA: "received close, then received more data?",
  RECEIVE_CHANNEL_HAS_NOT_BEEN_MADE_AVAILABLE: "Receive channel has not been made available",
  RECURSION_LIMIT_EXCEEDED: "recursion limit exceeded",
  REDIRECT_FROM_WSS_TO_WS: "redirect from WSS to WS",
  REDUCE_ARGUMENT_2_MUST_BE_AN_ITERABLE_OR_ASYNC_ITERABLE: "reduce() argument 2 must be an iterable or async iterable",
  REFINE_SEARCH_HINT: "Refine your search to display files",
  REGEX_IS_REMOVED_USE_PATTERN_INSTEAD_CODEREMOVEDKWARGS: "`regex` is removed. use `pattern` instead', code='removed-kwargs",
  RELOAD_STRATEGIES_SHOULD_OVERRIDE_SHOULD_RESTART: "Reload strategies should override should_restart()",
  REQUIRED: "required",
  REQUIRED_CLIENT_MAX_WINDOW_BITS: "required client_max_window_bits",
  REQUIREMENTSFROMSCRIPT_CAN_ONLY_BE_GIVEN_ONCE: "--requirements-from-script can only be given once",
  RESERVED_BITS_MUST_BE_0: "reserved bits must be 0",
  RESPONSE_CONTENT_LONGER_THAN_CONTENTLENGTH: "Response content longer than Content-Length",
  RESPONSE_CONTENT_SHORTER_THAN_CONTENTLENGTH: "Response content shorter than Content-Length",
  REVERSE_BOLD_WHITE_ON_BLUEREVERSE_BOLD_WHITE_ON_BLUE: "[reverse bold white on blue]reverse bold white on blue!",
  REVIEW_COMPLETE: "Review complete",
  REVIEW_COPY_MODE: "Copy mode",
  REVIEW_DB_PATH: "Database path",
  REVIEW_DIR_LAYOUT: "Directory layout",
  REVIEW_EXITING: "Exiting review safely",
  REVIEW_NOT_CONFIRMED: "REVIEW_NOT_CONFIRMED",
  REVIEW_OPTIONS: "Options",
  REVIEW_READY: "Ready to start",
  REVIEW_SHOW_RAW_JSON: "Show raw execution plan (JSON)",
  REVIEW_START: "Starting review of {count} files",
  RG_PACKET_ENDED_UNEXPECTEDLY: "RG packet ended unexpectedly.",
  ROOT_VALIDATOR_CANNOT_BE_APPLIED_TO_INSTANCE_METHODS: "`@root_validator` cannot be applied to instance methods",
  ROUTE_REQUIRES_WERKZEUG: "route() requires werkzeug",
  RUNNER_IS_CLOSED: "Runner is closed",
  RUNNING_EXPENSIVE_FUNCTION: "Running expensive function!",
  R_MUST_BE_NONNEGATIVE: "r must be non-negative",
  SAMPLE_FILES: "Sample files:",
  SAMPLE_RATE_CANT_BE_ZERO: "sample rate can't be zero",
  SANITY_ACTION_DISTRIBUTION: "Action distribution: {move}",
  SANITY_ACTION_STATUS_DISTRIBUTION: "Action status distribution",
  SANITY_CHECK_HEADER: "Pedro Organiza — Sanity Check",
  SANITY_DB_PATH: "Using database: {path}",
  SANITY_DONE: "Sanity check complete",
  SANITY_ERRORS: "Files in error state: {count}",
  SANITY_FP_CLUSTERS: "Fingerprint duplicate clusters: {count}",
  SANITY_LIFECYCLE_DISTRIBUTION: "Lifecycle distribution: {new}",
  SANITY_MISSING_DST: "Move actions missing destination: {count}",
  SANITY_MULTIPLE_PENDING_ACTIONS: "Files with multiple pending actions: {count}",
  SANITY_ORPHAN_ACTIONS: "Orphan actions detected: {count}",
  SANITY_SHA_CLUSTERS: "SHA-256 duplicate clusters: {count}",
  SANITY_TOTAL_FILES: "Total files: {count}",
  SCAN_ABORTED: "Scan aborted",
  SCAN_COMPLETED: "Scan completed successfully",
  SCAN_FAILED: "Scan failed",
  SCAN_IN_PROGRESS: "Scan in progress...",
  SCHEMA_IS_OUTDATED_RUN_PEDRO_MIGRATE: "⚠ Schema is outdated — run: pedro migrate",
  SDIST_MEMBERS: "~~~~~ sdist_members ~~~~~",
  SEARCHING: "Searching...",
  SECONDARY_FLAG_IS_NOT_VALID_FOR_NONBOOLEAN_FLAG: "Secondary flag is not valid for non-boolean flag.",
  SECONDS_MUST_BE_AN_INTEGER: "seconds must be an integer",
  SECURETRANSPORT_DOESNT_SUPPORT_CUSTOM_CIPHER_STRINGS: "SecureTransport doesn't support custom cipher strings",
  SECURETRANSPORT_DOES_NOT_SUPPORT_CERT_DIRECTORIES: "SecureTransport does not support cert directories",
  SECURETRANSPORT_ONLY_SUPPORTS_DUMPING_BINARY_CERTS: "SecureTransport only supports dumping binary certs",
  SECWEBSOCKETACCEPT: "Sec-WebSocket-Accept",
  SECWEBSOCKETACCEPT_MULTIPLE_VALUES: "Sec-WebSocket-Accept\", \"multiple values",
  SECWEBSOCKETKEY: "Sec-WebSocket-Key",
  SECWEBSOCKETKEY_MULTIPLE_VALUES: "Sec-WebSocket-Key\", \"multiple values",
  SECWEBSOCKETVERSION: "Sec-WebSocket-Version",
  SECWEBSOCKETVERSION_MULTIPLE_VALUES: "Sec-WebSocket-Version\", \"multiple values",
  SEEKING_BACKWARDS_IS_NOT_ALLOWED: "seeking backwards is not allowed",
  SELECT_TIMED_OUT: "select timed out",
  SEMAPHORE_RELEASED_TOO_MANY_TIMES: "semaphore released too many times",
  SEND_AWAITABLE_NOT_SET: "send awaitable not set",
  SEND_CHANNEL_HAS_NOT_BEEN_MADE_AVAILABLE: "Send channel has not been made available",
  SEP_MUST_BE_NONE_OR_A_STRING: "sep must be None or a string",
  SEQ_IS_NOT_DIVISIBLE_BY_N: "seq is not divisible by n.",
  SERIALIZER_IS_ALREADY_OPENED: "serializer is already opened",
  SERIALIZER_IS_CLOSED: "serializer is closed",
  SERIALIZER_IS_NOT_OPENED: "serializer is not opened",
  SERVER_MAX_WINDOW_BITS_MUST_BE_BETWEEN_8_AND_15: "server_max_window_bits must be between 8 and 15",
  SERVER_REJECTED_REQUEST_WRONG_USERNAME_OR_PASSWORD: "Server rejected request: wrong username or password",
  SETUPCFG: "~~~~~ setup.cfg ~~~~~",
  SHOULDNT_BE_ABLE_TO_GET_HERE: "Shouldn't be able to get here",
  SHOULD_PASS_A_UNICODE_STRING_TO_THE_FUNCTION_RATHER_THAN_A_BYTE_STRING: "should pass a unicode string to the function rather than a byte string.",
  SH_PACKET_ENDED_UNEXPECTEDLY: "SH packet ended unexpectedly.",
  SIZE_MUST_NOT_BE_NEGATIVE: "size must not be negative",
  SLICES_WITH_STEP1_ARE_NOT_SUPPORTED: "slices with step!=1 are not supported",
  SLICE_STEP_CANNOT_BE_ZERO: "slice step cannot be zero",
  SOLICITED_PONG_NOT_FOUND_IN_PINGS: "solicited pong not found in pings",
  SOURCE_FILE_IS_NOT_A_PYTHON_FILE: "Source file is not a Python file",
  SOURCE_MISSING: "SOURCE_MISSING",
  SOURCE_PATH_MISSING: "SOURCE_PATH_MISSING",
  SPECIAL_DEVICES_NOT_SUPPORTED_BY_SYSTEM: "special devices not supported by system",
  SPECIFYING_CONFIG_IN_TWO_PLACES_IS_AMBIGUOUS_USE_EITHER_CONFIG_ATTRIBUTE_OR_CLASS_KWARGS: "Specifying config in two places is ambiguous, use either Config attribute or class kwargs",
  SPECIFYING_TARGETS_VIA_THE_FLAGS_PRAGMA_IS_NOT_SUPPORTED: "Specifying targets via the flags pragma is not supported.",
  SPEC_OBJECTS_ARE_UNHASHABLE: "Spec objects are unhashable",
  SRC_NOT_FOUND: "Source directory not found",
  SSLNONE_IS_INCOMPATIBLE_WITH_A_WSS_URI: "ssl=None is incompatible with a wss:// URI",
  SSL_ARGUMENT_IS_INCOMPATIBLE_WITH_A_WS_URI: "ssl argument is incompatible with a ws:// URI",
  STARTING_PATH_NOT_FOUND: "Starting path not found",
  STARTUP_SCAN_DRY_RUN: "Dry run",
  STARTUP_SCAN_RUNNING_HUGE: "Very large library. Please be patient, the scan is still running.",
  STARTUP_SCAN_RUNNING_LONG: "Still scanning… this is normal for medium libraries.",
  STARTUP_SCAN_RUNNING_VERY_LONG: "Large library detected. This may take several minutes.",
  STATE: "state",
  STATS: "Stats:",
  STATUS_CODE_MUST_BE_INTEGER: "status code must be integer",
  STEP_ARGUMENT_MUST_BE_A_NONZERO_INTEGER_OR_NONE: "step argument must be a non-zero integer or None.",
  STEP_MUST_BE_1: "step must be >= 1",
  STOPPED_VIA_KEYBOARDINTERRUPT: "stopped via KeyboardInterrupt",
  STREAM_CONSUMED: "Stream consumed",
  STREAM_ENDED: "stream ended",
  STREAM_INFO_BLOCK_NOT_FOUND: "Stream info block not found",
  STREAM_INFO_HAS_INVALID_LENGTH: "stream info has invalid length",
  STREAM_OF_FRAMES_ENDED: "stream of frames ended",
  STRING_ENDED_UNSAFE: "string ended unsafe",
  STRING_IS_TOO_LARGE: "String is too large",
  SUBCLASS_SHOULD_OVERRIDE: "Subclass should override",
  SUBINTERPRETERS_REQUIRE_AT_LEAST_PYTHON_313: "subinterpreters require at least Python 3.13",
  SUBPROTOCOLS_MUST_BE_A_LIST: "subprotocols must be a list",
  SUBPROTOCOLS_MUST_BE_A_LIST_NOT_A_STR: "subprotocols must be a list, not a str",
  SUCCESS: "success",
  SUPPORT_FOR_THE_TEST_COMMAND_WAS_REMOVED_IN_SETUPTOOLS_72: "Support for the test command was removed in Setuptools 72",
  SYNC_NOT_FOUND: "sync not found",
  SYNTAX_PYTHON3_ICNSIMAGEPLUGINPY_FILE: "Syntax: python3 IcnsImagePlugin.py [file]",
  SYNTAX_PYTHON3_IMAGESHOWPY_IMAGEFILE_TITLE: "Syntax: python3 ImageShow.py imagefile [title]",
  SYNTAX_PYTHON3_SPIDERIMAGEPLUGINPY_INFILE_OUTFILE: "Syntax: python3 SpiderImagePlugin.py [infile] [outfile]",
  TAGS_END: "tags:\", end=\" ",
  TAG_HANDLE_MUST_NOT_BE_EMPTY: "tag handle must not be empty",
  TAG_IS_NOT_SPECIFIED: "tag is not specified",
  TAG_MUST_NOT_BE_EMPTY: "tag must not be empty",
  TAG_NAME_EMPTY: "TAG_NAME_EMPTY",
  TAG_PREFIX_MUST_NOT_BE_EMPTY: "tag prefix must not be empty",
  TARGET_PATH_MISSING: "TARGET_PATH_MISSING",
  TARINFOTYPE_MUST_NOT_BE_NONE: "TarInfo.type must not be None",
  TCP_PORT_NUMBER_OUT_OF_RANGE: "TCP port number out of range",
  TEMPORARY_DIRECTORY: "Temporary directory:",
  TEST_OUTPUT: "Test output:",
  TEST_RAISE: "TEST_RAISE",
  TEXTUALはPYTHONの高速アプリケーション開発フレームワークです: "TextualはPythonの高速アプリケーション開発フレームワークです",
  THERE_IS_NO_ACTIVE_CLICK_CONTEXT: "There is no active click context.",
  THERE_IS_NO_NEST_BEHIND_THIS_KEY: "There is no nest behind this key",
  THE_BOSS_IS_GOING_TO_HEAR_ABOUT_THIS: "The boss is going to hear about this",
  THE_CONNECTION_IS_BUSY: "The connection is busy.",
  THE_CONTENTDISPOSITION_HEADER_FIELD_NAME_MUST_BE_PROVIDED: "The Content-Disposition header field \"name\" must be provided.",
  THE_CONTENT_FOR_THIS_RESPONSE_WAS_ALREADY_CONSUMED: "The content for this response was already consumed",
  THE_CURRENT_TASK_IS_NOT_HOLDING_THE_UNDERLYING_LOCK: "The current task is not holding the underlying lock",
  THE_CURRENT_TASK_IS_NOT_HOLDING_THIS_LOCK: "The current task is not holding this lock",
  THE_DOCUTILS_PACKAGE_IS_NEEDED: "The docutils package is needed.",
  THE_ENCODER_ARGUMENT_IS_NO_LONGER_SUPPORTED_USE_FIELD_SERIALIZERS_INSTEAD: "The `encoder` argument is no longer supported; use field serializers instead.",
  THE_FIRST_ARGUMENT_MUST_BE_CALLABLE: "the first argument must be callable",
  THE_MODELS_AS_DICT_ARGUMENT_IS_NO_LONGER_SUPPORTED_USE_A_MODEL_SERIALIZER_INSTEAD: "The `models_as_dict` argument is no longer supported; use a model serializer instead.",
  THE_MODE_ARGUMENT_SHOULD_BE_TEXT_OR_BINARY: "The \"mode\" argument should be \"text\" or \"binary\".",
  THE_READ_OPERATION_TIMED_OUT: "The read operation timed out",
  THE_SEGMENTS_ARE_THEN_PROCESSED_TO_PRODUCE_THE_FOLLOWING_OUTPUTN: "The Segments are then processed to produce the following output:\n",
  THE_SERVER_DOESNT_SUPPORT_THE_WEBSOCKET_DENIAL_RESPONSE_EXTENSION: "The server doesn't support the Websocket Denial Response extension.",
  THE_SERVER_DOES_NOT_SUPPORT_STATE_IN_THE_LIFESPAN_SCOPE: "The server does not support \"state\" in the lifespan scope.",
  THE_SOCKET_MUST_BE_BOUND_TO_A_LOCAL_ADDRESS: "the socket must be bound to a local address",
  THE_SOCKET_MUST_BE_CONNECTED: "the socket must be connected",
  THE_SOCKET_TIMED_OUT: "The socket timed out",
  THE_URL_FOR_METHOD_CAN_ONLY_BE_USED_INSIDE_A_STARLETTE_APPLICATION_OR_WITH_A_ROUTER: "The `url_for` method can only be used inside a Starlette application or with a router.",
  THIS_CANCEL_SCOPE_IS_NOT_ACTIVE: "This cancel scope is not active",
  THIS_CANNOT_BE_UNDONE: "This CANNOT be undone.",
  THIS_FUNCTION_MUST_BE_USED_INSIDE_ANOTHER_FUNCTION: "This function must be used inside another function",
  THIS_PORTAL_IS_NOT_RUNNING: "This portal is not running",
  THIS_TOKEN_DOES_NOT_BELONG_TO_THIS_RUNVAR: "This token does not belong to this RunVar",
  THIS_TOKEN_HAS_ALREADY_BEEN_USED: "This token has already been used",
  TIMED_OUT: "timed out",
  TIMED_OUT_DURING_OPENING_HANDSHAKE: "timed out during opening handshake",
  TIMED_OUT_WAITING_FOR_CONNECTION: "Timed out waiting for connection.",
  TIMED_OUT_WHILE_CONNECTING_TO_HTTP_PROXY: "timed out while connecting to HTTP proxy",
  TIMED_OUT_WHILE_WAITING_FOR_HANDSHAKE_REQUEST: "timed out while waiting for handshake request",
  TIMED_OUT_WHILE_WAITING_FOR_HANDSHAKE_RESPONSE: "timed out while waiting for handshake response",
  TIMEOUT_IS_REQUIRED: "timeout is required",
  TIMEOUT_TIMER_HAS_ALREADY_BEEN_STARTED: "Timeout timer has already been started.",
  TIMEOUT_WAITING_FOR_SUBPROCESS: "Timeout waiting for subprocess",
  TIMESTAMP_MUST_BE_03: "timestamp must be 0..3",
  TOML_DOES_NOT_SUPPORT_OFFSET_TIMES: "TOML does not support offset times",
  TOO_LARGE_DATA: "Too large data",
  TOO_LITTLE_DATA_FOR_DECLARED_CONTENTLENGTH: "Too little data for declared Content-Length",
  TOO_MANY_ARGUMENTS: "Too many arguments",
  TOO_MANY_HTTP_HEADERS: "too many HTTP headers",
  TOO_MANY_ITERATIONS_WHEN_CHECKING_A_LOOP: "Too many iterations when checking a loop",
  TOO_MANY_REDIRECTS: "too many redirects",
  TOO_MUCH_DATA_FOR_DECLARED_CONTENTLENGTH: "Too much data for declared Content-Length",
  TOTAL_TOKENS_MUST_BE_0: "total_tokens must be >= 0",
  TOTAL_TOKENS_MUST_BE_1: "total_tokens must be >= 1",
  TOTAL_TOKENS_MUST_BE_AN_INT_OR_MATHINF: "total_tokens must be an int or math.inf",
  TO_AVOID_CONFUSION___CONFIG___AND___BASE___CANNOT_BE_USED_TOGETHER: "to avoid confusion __config__ and __base__ cannot be used together",
  TO_DEFINE_ROOT_MODELS_USE_PYDANTICROOTMODEL_RATHER_THAN_A_FIELD_CALLED___ROOT__: "To define root models, use `pydantic.RootModel` rather than a field called '__root__'",
  TQDM_OBJECT_IS_NOT_REVERSIBLE: "'tqdm' object is not reversible",
  TRACEBACK_MOST_RECENT_CALL_LAST: "Traceback (most recent call last):",
  TRACK_HAS_NO_AUDIO_DATA: "track has no audio data",
  TRANSFER_CODINGS_ARENT_SUPPORTED: "transfer codings aren't supported",
  TRIED_TO_DIRECTLY_INSTANTIATE_PROTOCOLERROR: "tried to directly instantiate ProtocolError",
  TRUNCATED: "truncated",
  TRUNCATED_CONTENT: "truncated content",
  TRUNCATED_DATA: "truncated data",
  TRUNCATED_HEADER: "Truncated header",
  TRUNCATED_HEADER_2: "truncated header",
  TRUSTSTORE_REQUIRES_PYTHON_310_OR_LATER: "truststore requires Python 3.10 or later",
  TRUSTSTORE_REQUIRES_THE_SSL_MODULE: "truststore requires the 'ssl' module",
  TRYING_TO_DECODE_WITH_PICKLE_WITH_ALLOW_PICKLEFALSE: "Trying to decode with pickle with allow_pickle=False",
  TTA_HEADER_NOT_FOUND: "TTA header not found",
  TYPEALIASTYPE_NAME_MUST_BE_A_STRING: "TypeAliasType name must be a string",
  TYPECODE_MUST_HAVE_INT_TYPE: "typecode must have int type.",
  TYPECODE_SHOULD_BE_0127: "typecode should be 0-127",
  TYPEDDICT_DOES_NOT_SUPPORT_INSTANCE_AND_CLASS_CHECKS: "TypedDict does not support instance and class checks",
  TYPEDDICT_TAKES_NO_KEYWORD_ARGUMENTS: "TypedDict takes no keyword arguments",
  TYPE_ALIASES_SHOULD_BE_EXPANDED_BEFORE_ACCEPTING_THIS_VISITOR: "Type aliases should be expanded before accepting this visitor",
  TYPE_ALIAS_IS_NOT_CALLABLE: "Type alias is not callable",
  TYPE_ANNOTATED_CANNOT_BE_INSTANTIATED: "Type Annotated cannot be instantiated.",
  TYPE_IS_NONE: "Type is None",
  TYPE_PARAMETERS_SHOULD_BE_PLACED_ON_TYPINGGENERIC_NOT_BASEMODEL: "Type parameters should be placed on typing.Generic, not BaseModel",
  TYPE_PARAMETERS_SHOULD_BE_PLACED_ON_TYPINGGENERIC_NOT_GENERICMODEL: "Type parameters should be placed on typing.Generic, not GenericModel",
  TYPE_PARAMS_MUST_BE_A_TUPLE: "type_params must be a tuple",
  TYPINGSELF_IS_INVALID_IN_THIS_CONTEXT_CODEINVALIDSELFTYPE: "`typing.Self` is invalid in this context', code='invalid-self-type",
  TYPING_EXTENSIONSANY_CANNOT_BE_USED_WITH_ISINSTANCE: "typing_extensions.Any cannot be used with isinstance()",
  UNABLE_TO_ALLOCATE_MEMORY: "Unable to allocate memory!",
  UNABLE_TO_DETERMINE_WHETHER_FP_IS_CLOSED: "Unable to determine whether fp is closed.",
  UNABLE_TO_FIND_FINAL_OGG_HEADER: "unable to find final Ogg header",
  UNABLE_TO_GET_LEGACY_WINDOWS_CONSOLE_MODE: "Unable to get legacy Windows Console Mode",
  UNABLE_TO_GET_TIMESCALE: "Unable to get timescale",
  UNABLE_TO_PARSE_IDENTIFICATION: "unable to parse identification",
  UNABLE_TO_PARSE_MACHINE_AND_SECTION_INFORMATION: "unable to parse machine and section information",
  UNABLE_TO_POP_BASE_THEME: "Unable to pop base theme",
  UNABLE_TO_READ_FULL_DATA: "unable to read full data",
  UNABLE_TO_RESOLVE_LINK_INSIDE_ARCHIVE: "unable to resolve link inside archive",
  UNABLE_TO_REWIND_REQUEST_BODY_FOR_REDIRECT: "Unable to rewind request body for redirect.",
  UNBUFFERED_STREAMS_MUST_BE_BINARY: "unbuffered streams must be binary",
  UNDISCERNIBLE_MODE: "undiscernible mode",
  UNEXPECTED_CALLS_TO_LOOPCALL_EXCEPTION_HANDLER: "Unexpected calls to loop.call_exception_handler():",
  UNEXPECTED_CLIENT_MAX_WINDOW_BITS: "unexpected client_max_window_bits",
  UNEXPECTED_CONDITION_TESTING_FOR_WRITABLE_DIRECTORY: "Unexpected condition testing for writable directory",
  UNEXPECTED_CONTINUATION_FRAME: "unexpected continuation frame",
  UNEXPECTED_END_OF_DATA: "unexpected end of data",
  UNEXPECTED_END_OF_INPUT: "unexpected end of input",
  UNEXPECTED_END_OF_STREAM: "unexpected end of stream",
  UNEXPECTED_OPCODE: "unexpected opcode",
  UNIX_ROUTE_REQUIRES_WERKZEUG: "unix_route() requires werkzeug",
  UNKNOWN_CHARACTER_IN_UNICODEDATA: "Unknown character in unicodedata",
  UNKNOWN_DUP_SUBCOMMAND: "Unknown dup subcommand",
  UNKNOWN_GENRE: "unknown genre",
  UNKNOWN_VERBOSITY: "Unknown verbosity",
  UNORDERED_TYPES_ARE_NOT_ALLOWED: "Unordered types are not allowed",
  UNPACK_FAILED_INCOMPLETE_INPUT: "Unpack failed: incomplete input",
  UNPACK_MUST_BE_USED_WITH_A_TUPLE_TYPE: "Unpack[...] must be used with a tuple type",
  UNREACHABLE: "Unreachable",
  UNSUPPORTED_CLIENT_MAX_WINDOW_BITS: "unsupported client_max_window_bits",
  UNSUPPORTED_COMPRESSION_METHOD: "unsupported compression method",
  UNSUPPORTED_FORMAT_ID: "Unsupported format ID",
  UNSUPPORTED_FORMAT_VERSION: "Unsupported format version",
  UNSUPPORTED_PROXY: "unsupported proxy",
  UNSUPPORTED_REQUEST_BODY: "unsupported request body",
  UNSUPPORTED_SERVER_MAX_WINDOW_BITS: "unsupported server_max_window_bits",
  UNSUPPORTED_STSD_VERSION: "Unsupported stsd version",
  UNSUPPORTED_TYPE: "unsupported type",
  UNSUPPORTED_TYPE_MUST_BE_EITHER_BASEMODEL_OR_DATACLASS: "Unsupported type, must be either BaseModel or dataclass",
  UNSUPPORTED_VERSION: "unsupported version",
  UNSUPPORTED_WHEEL_FORMAT_DISTINFO_NOT_FOUND: "unsupported wheel format. .dist-info not found",
  UPDATE_TAKES_AT_LEAST_1_ARGUMENT_0_GIVEN: "update() takes at least 1 argument (0 given)",
  URL_HAS_AN_INVALID_LABEL: "URL has an invalid label.",
  USER_BASE_DIRECTORY_IS_NOT_SPECIFIED: "User base directory is not specified",
  USER_PREFIX: "--user\", \"--prefix",
  USE_THE_OVERWRITEPARAMETER_INSTEAD: "Use the `overwrite`-parameter instead.",
  UVLOOPRUN_USES_A_NONUVLOOP_EVENT_LOOP: "uvloop.run() uses a non-uvloop event loop",
  VALIDATION_SHOULD_HAVE_FAILED: "Validation should have failed",
  VALIDATOR_WITH_NO_FIELDS_SPECIFIED: "validator with no fields specified",
  VALUE_NOT_BYTES: "value not bytes",
  VALUE_NOT_STR: "value not str",
  VALUE_TYPE_MUST_BE_0_1_OR_2: "value type must be 0, 1, or 2",
  VARIABLE_TUPLES_CAN_ONLY_HAVE_ONE_TYPE: "Variable tuples can only have one type",
  VARIANCE_CANNOT_BE_SPECIFIED_WITH_INFER_VARIANCE: "Variance cannot be specified with infer_variance.",
  VBRI_HEADER_TRUNCATED: "VBRI header truncated",
  VCOMMENT_REQUIRES_BYTES_OR_A_FILELIKE: "VComment requires bytes or a file-like",
  VENDOR_NEEDS_TO_BE_STR: "vendor needs to be str",
  VERIFY_CRL_CHECK_LEAF_NOT_IMPLEMENTED_FOR_MACOS: "VERIFY_CRL_CHECK_LEAF not implemented for macOS",
  VERTEX_EXISTS: "vertex exists",
  VIRTUAL_ENVIRONMENT: "Virtual environment:",
  WARNING_FORCEUPPERCASEBUILTINS_IS_DEPRECATED_MYPY_ONLY_SUPPORTS_PYTHON_39: "Warning: --force-uppercase-builtins is deprecated; mypy only supports Python 3.9+",
  WARNING_STRICTCONCATENATE_IS_DEPRECATED_USE_EXTRACHECKS_INSTEAD: "Warning: --strict-concatenate is deprecated; use --extra-checks instead",
  WARN_FAILED_TO_LOAD_TRANSLATIONS_USING_RAW_OUTPUT: "[WARN] Failed to load translations, using raw output.",
  WAS_NOT_ABLE_TO_DETERMINE_BINARY_STREAM_FOR_SYSSTDERR: "Was not able to determine binary stream for sys.stderr.",
  WAS_NOT_ABLE_TO_DETERMINE_BINARY_STREAM_FOR_SYSSTDIN: "Was not able to determine binary stream for sys.stdin.",
  WAS_NOT_ABLE_TO_DETERMINE_BINARY_STREAM_FOR_SYSSTDOUT: "Was not able to determine binary stream for sys.stdout.",
  WATCH_THREAD_UNEXPECTEDLY_RECEIVED_A_SIGNAL: "watch thread unexpectedly received a signal",
  WEBSOCKET_CONNECTION_ISNT_ESTABLISHED_YET: "WebSocket connection isn't established yet",
  WEBSOCKET_IS_NOT_CONNECTED_NEED_TO_CALL_ACCEPT_FIRST: "WebSocket is not connected. Need to call \"accept\" first.",
  WHEEL_IS_MISSING_WHEELVERSION: "WHEEL is missing Wheel-Version",
  WHEEL_MEMBERS: "~~~~~ wheel_members ~~~~~",
  WHITE_ON_BLACKWHITE_ON_BLACK: "[white on black]white on black!",
  WIDTH_AND_HEIGHT_DO_NOT_MATCH: "width and height do not match",
  WINDOW_SIZE_MUST_BE_AT_LEAST_1: "window size must be at least 1",
  WINDOW_SIZE_MUST_BE_AT_LEAST_1_2: "window_size must be at least 1",
  WIZARD_STEP_DB: "Database",
  WIZARD_STEP_OPTIONS: "Options",
  WIZARD_STEP_PATHS: "Paths",
  WIZARD_STEP_REVIEW: "Review",
  WIZARD_STEP_SCAN: "Scan",
  WIZARD_STEP_WELCOME: "Welcome",
  WIZARD_TITLE: "Startup Wizard",
  WIZARD_WELCOME_SUBTITLE: "This wizard will guide you through the initial setup",
  WIZARD_WELCOME_TITLE: "Welcome to Pedro Organiza",
  WRITE: "write",
  WRITELINES: "writelines",
  WRITING_TO: "writing to",
  XING_HEADER_TRUNCATED: "Xing header truncated",
  XXX: "xxx",
  YELLOWYELLOW: "[yellow]yellow!",
  YES: "Yes",
  YOU_CAN_ONLY_MERGE_INTO_COOKIEJAR: "You can only merge into CookieJar",
  YOU_CAN_ONLY_SEND_PREPAREDREQUESTS: "You can only send PreparedRequests.",
  YOU_MUST_HAVE_THE_CONFIG_ATTRIBUTE_ORM_MODETRUE_TO_USE_FROM_ORM: "You must have the config attribute orm_mode=True to use from_orm",
  YOU_MUST_SPECIFY_RPMBASE_IN_RPM_2_MODE: "you must specify --rpm-base in RPM 2 mode",
  YOU_NEED_TO_SPECIFY_EXACTLY_ONE_ARGUMENT: "You need to specify exactly one argument",
  YOU_NEED_TO_USE_PROGRESS_BARS_IN_A_WITH_BLOCK: "You need to use progress bars in a with block.",
  ZLIB_MODULE_IS_NOT_AVAILABLE: "zlib module is not available",
  _2: "----------------------------",
  _3: "--------------",
  _4: "-------------------------------------------",
  _5: "---",
  _6: "---------------",
  _7: "??????????",
  _8: "????-??-?? ??:??:??",
  _9: "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
  __INIT___GOT_AN_UNEXPECTED_KEYWORD_ARGUMENT_MULTIPLE: "__init__() got an unexpected keyword argument 'multiple'.",
  アプリケーションは1670万色を使用でき: "アプリケーションは1670万色を使用でき",
};
