# core/export_js.py
import json


HEADER = "// Generated by Dennis the Forge\n"

def export_js(plan: dict, fp):
    # Flatten into token map if tokens exist
    mapping = {}
    for c in plan["changes"]:
        token = c.get("token")
        if token:
            mapping[token] = c["replacement"]

    fp.write(HEADER)
    fp.write("export default ")
    json.dump(mapping, fp, ensure_ascii=False, indent=2, sort_keys=True)
    fp.write(";\n")